[build]
  command = "pnpm build"
  publish = "dist"

[[redirects]]
  from = "https://www.festaai.com.br/*"
  to = "https://festaai.com.br/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
