create table public.eventos (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  cliente_nome text not null,
  cliente_telefone text,
  cliente_email text,
  aniversariante_nome text,
  aniversariante_data_nascimento date,
  data_evento date,
  hora_evento time,
  quantidade_convidados integer,
  pacote_id bigint,
  pacote_nome text,
  valor_pacote numeric(12, 2) not null default 0,
  valor_adicionais numeric(12, 2) not null default 0,
  valor_total numeric(12, 2) not null default 0,
  valor_entrada numeric(12, 2) not null default 0,
  funil text not null default 'vendas',
  etapa text not null default 'contato_inicial',
  status_interno text not null default 'ativo',
  tipo_evento text not null default 'festa',
  origem text,
  motivo_perda text,
  observacoes text,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint eventos_funil_check check (funil in ('vendas', 'festa', 'executadas')),
  constraint eventos_etapa_check check (
    etapa in (
      'contato_inicial',
      'proposta_enviada',
      'negociacao',
      'visita_agendada',
      'fechado',
      'perdido',
      'boas_vindas',
      'planejamento',
      'contrato',
      'organizacao',
      'festa_pronta',
      'aguardando_feedback',
      'redes_sociais',
      'oportunidade_futura'
    )
  ),
  constraint eventos_funil_etapa_check check (
    (
      funil = 'vendas'
      and etapa in ('contato_inicial', 'proposta_enviada', 'negociacao', 'visita_agendada', 'fechado', 'perdido')
    )
    or (
      funil = 'festa'
      and etapa in ('boas_vindas', 'planejamento', 'contrato', 'organizacao', 'festa_pronta')
    )
    or (
      funil = 'executadas'
      and etapa in ('aguardando_feedback', 'redes_sociais', 'oportunidade_futura')
    )
  ),
  constraint eventos_status_interno_check check (status_interno in ('novo', 'ativo', 'pendente', 'finalizado', 'perdido', 'cancelado')),
  constraint eventos_tipo_evento_check check (tipo_evento in ('festa', 'visita')),
  constraint eventos_quantidade_convidados_check check (quantidade_convidados is null or quantidade_convidados >= 0),
  constraint eventos_valores_check check (
    valor_pacote >= 0
    and valor_adicionais >= 0
    and valor_total >= 0
    and valor_entrada >= 0
  )
);

create index eventos_tenant_id_idx on public.eventos (tenant_id);
create index eventos_tenant_funil_etapa_idx on public.eventos (tenant_id, funil, etapa);
create index eventos_tenant_data_evento_idx on public.eventos (tenant_id, data_evento);
create index eventos_tenant_status_idx on public.eventos (tenant_id, status_interno);
create index eventos_created_by_idx on public.eventos (created_by);

create trigger set_eventos_updated_at
before update on public.eventos
for each row
execute function public.set_updated_at();

alter table public.eventos enable row level security;

create policy "eventos_select_members"
on public.eventos
for select
to authenticated
using (public.is_tenant_member(tenant_id));

create policy "eventos_insert_members"
on public.eventos
for insert
to authenticated
with check (public.is_tenant_member(tenant_id));

create policy "eventos_update_members"
on public.eventos
for update
to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

create policy "eventos_delete_admins"
on public.eventos
for delete
to authenticated
using (public.has_tenant_role(tenant_id, array['owner', 'admin']));
