-- Aceite dos termos do módulo de contratos (habilitação por tenant)

create table if not exists public.tenant_contract_module_acceptances (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  terms_version integer not null,
  accepted_by_user_id uuid not null references auth.users(id) on delete restrict,
  accepted_by_name text not null,
  accepted_by_email text,
  acceptance_text text not null,
  user_agent text,
  accepted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint tenant_contract_module_acceptances_name_check
    check (char_length(trim(accepted_by_name)) > 0),
  constraint tenant_contract_module_acceptances_text_check
    check (char_length(trim(acceptance_text)) > 0),
  constraint tenant_contract_module_acceptances_tenant_version_unique
    unique (tenant_id, terms_version)
);

create index if not exists tenant_contract_module_acceptances_tenant_idx
  on public.tenant_contract_module_acceptances (tenant_id, terms_version desc);

alter table public.tenant_contract_module_acceptances enable row level security;

drop policy if exists "tenant_contract_module_acceptances_select_tenant_member"
  on public.tenant_contract_module_acceptances;
create policy "tenant_contract_module_acceptances_select_tenant_member"
on public.tenant_contract_module_acceptances
for select to authenticated
using (public.is_tenant_member(tenant_id));

drop policy if exists "tenant_contract_module_acceptances_insert_tenant_admin"
  on public.tenant_contract_module_acceptances;
create policy "tenant_contract_module_acceptances_insert_tenant_admin"
on public.tenant_contract_module_acceptances
for insert to authenticated
with check (public.has_tenant_role(tenant_id, array['owner', 'admin']));
