create table public.tenant_satisfaction_survey_questions (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  label text not null,
  question_key text,
  question_type text not null default 'textarea',
  required boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0,
  config jsonb not null default '{}'::jsonb,
  is_system boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_satisfaction_survey_questions_label_check check (char_length(trim(label)) > 0),
  constraint tenant_satisfaction_survey_questions_type_check check (
    question_type in ('scale', 'single_choice', 'textarea')
  ),
  constraint tenant_satisfaction_survey_questions_key_unique unique (tenant_id, question_key),
  constraint tenant_satisfaction_survey_questions_id_tenant_id_key unique (id, tenant_id)
);

create table public.evento_satisfaction_responses (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  evento_id bigint not null,
  question_id bigint not null,
  value text,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint evento_satisfaction_responses_evento_tenant_fkey
    foreign key (evento_id, tenant_id)
    references public.eventos(id, tenant_id)
    on delete cascade,
  constraint evento_satisfaction_responses_question_tenant_fkey
    foreign key (question_id, tenant_id)
    references public.tenant_satisfaction_survey_questions(id, tenant_id)
    on delete cascade,
  constraint evento_satisfaction_responses_unique unique (evento_id, question_id)
);

create index tenant_satisfaction_survey_questions_tenant_idx
  on public.tenant_satisfaction_survey_questions (tenant_id, sort_order);

create index evento_satisfaction_responses_tenant_evento_idx
  on public.evento_satisfaction_responses (tenant_id, evento_id);

create trigger set_tenant_satisfaction_survey_questions_updated_at
before update on public.tenant_satisfaction_survey_questions
for each row execute function public.set_updated_at();

create trigger set_evento_satisfaction_responses_updated_at
before update on public.evento_satisfaction_responses
for each row execute function public.set_updated_at();

alter table public.tenant_satisfaction_survey_questions enable row level security;
alter table public.evento_satisfaction_responses enable row level security;

create policy "tenant_satisfaction_survey_questions_members_all"
on public.tenant_satisfaction_survey_questions
for all to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

create policy "evento_satisfaction_responses_select_members"
on public.evento_satisfaction_responses
for select to authenticated
using (public.is_tenant_member(tenant_id));

create policy "evento_satisfaction_responses_insert_members"
on public.evento_satisfaction_responses
for insert to authenticated
with check (public.is_tenant_member(tenant_id));

create policy "evento_satisfaction_responses_update_members"
on public.evento_satisfaction_responses
for update to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

create policy "evento_satisfaction_responses_delete_members"
on public.evento_satisfaction_responses
for delete to authenticated
using (public.is_tenant_member(tenant_id));

create or replace function public.seed_tenant_satisfaction_survey_questions(p_tenant_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.tenant_satisfaction_survey_questions (
    tenant_id, label, question_key, question_type, required, active, sort_order, config, is_system
  )
  values
    (
      p_tenant_id,
      'De 0 a 10, quanto você indicaria a {{nome_empresa}} para outra mãe?',
      'nps_indicacao',
      'scale',
      true,
      true,
      1,
      '{"min": 0, "max": 10}'::jsonb,
      true
    ),
    (
      p_tenant_id,
      'Como você avalia sua experiência geral com a festa?',
      'experiencia_geral',
      'single_choice',
      true,
      true,
      2,
      '{"options": ["Excelente", "Muito boa", "Boa", "Regular", "Ruim"]}'::jsonb,
      true
    ),
    (
      p_tenant_id,
      'O atendimento antes da festa foi claro e acolhedor?',
      'atendimento_pre_festa',
      'single_choice',
      false,
      true,
      3,
      '{"options": ["Sim, muito", "Sim", "Mais ou menos", "Não"]}'::jsonb,
      true
    ),
    (
      p_tenant_id,
      'Como você avalia a organização e atendimento da equipe no dia da festa?',
      'organizacao_equipe',
      'single_choice',
      false,
      true,
      4,
      '{"options": ["Excelente", "Muito boa", "Boa", "Regular", "Ruim"]}'::jsonb,
      true
    ),
    (
      p_tenant_id,
      'A festa aconteceu conforme o combinado?',
      'conforme_combinado',
      'single_choice',
      false,
      true,
      5,
      '{"options": ["Sim, tudo certinho", "Quase tudo", "Algumas coisas não saíram como esperado"]}'::jsonb,
      true
    ),
    (
      p_tenant_id,
      'Teve algo que você sentiu falta ou que poderíamos melhorar?',
      'melhorias',
      'textarea',
      false,
      true,
      6,
      '{}'::jsonb,
      true
    ),
    (
      p_tenant_id,
      'Seu filho(a) aproveitou a festa como você esperava?',
      'crianca_aproveitou',
      'single_choice',
      false,
      true,
      7,
      '{"options": ["Sim, muito", "Sim", "Mais ou menos", "Não"]}'::jsonb,
      true
    ),
    (
      p_tenant_id,
      'Você contrataria a {{nome_empresa}} novamente?',
      'contrataria_novamente',
      'single_choice',
      true,
      true,
      8,
      '{"options": ["Sim", "Talvez", "Não"]}'::jsonb,
      true
    ),
    (
      p_tenant_id,
      'Deixe aqui um depoimento sobre sua experiência na {{nome_empresa}}',
      'depoimento_aberto',
      'textarea',
      false,
      true,
      9,
      '{}'::jsonb,
      true
    )
  on conflict (tenant_id, question_key) do nothing;
end;
$$;

select public.seed_tenant_satisfaction_survey_questions(t.id)
from public.tenants t;

create or replace function public.seed_satisfaction_survey_on_tenant_create()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.seed_tenant_satisfaction_survey_questions(new.id);
  return new;
end;
$$;

create trigger seed_satisfaction_survey_on_tenant_create
after insert on public.tenants
for each row
execute function public.seed_satisfaction_survey_on_tenant_create();

alter table public.tenant_guided_setup_progress
  drop constraint if exists tenant_guided_setup_progress_current_step_check;

alter table public.tenant_guided_setup_progress
  add constraint tenant_guided_setup_progress_current_step_check
  check (
    current_step in (
      'company_profile',
      'packages',
      'adicionais',
      'estrutura',
      'financeiro',
      'checklist',
      'contrato',
      'formulario',
      'pesquisa_avaliacao',
      'whatsapp',
      'automacoes',
      'completed'
    )
  );
