-- Agendamento de disparo WhatsApp (Evolution) ao entrar em Boas Vindas.
alter table public.eventos
  add column if not exists boas_vindas_whatsapp_agendado_em timestamptz;

create index if not exists eventos_boas_vindas_whatsapp_pendente_idx
  on public.eventos (tenant_id, boas_vindas_whatsapp_agendado_em)
  where boas_vindas_whatsapp_agendado_em is not null;

-- Conexão Evolution por usuário dentro do tenant (WIP substituído em 20260617215743).
create table if not exists public.tenant_evolution_connections (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  instance_name text not null,
  status text not null default 'disconnected',
  qr_code_base64 text,
  phone_number text,
  last_error text,
  connected_at timestamptz,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_evolution_connections_user_tenant_unique unique (tenant_id, user_id),
  constraint tenant_evolution_connections_instance_name_unique unique (instance_name),
  constraint tenant_evolution_connections_status_check check (
    status in ('disconnected', 'connecting', 'connected', 'error')
  )
);

create index tenant_evolution_connections_tenant_user_idx
  on public.tenant_evolution_connections (tenant_id, user_id);

create trigger set_tenant_evolution_connections_updated_at
before update on public.tenant_evolution_connections
for each row execute function public.set_updated_at();

alter table public.tenant_evolution_connections enable row level security;

create policy "tenant_evolution_connections_select_own"
on public.tenant_evolution_connections
for select to authenticated
using (
  public.is_tenant_member(tenant_id)
  and user_id = auth.uid()
);

create policy "tenant_evolution_connections_insert_own"
on public.tenant_evolution_connections
for insert to authenticated
with check (
  public.is_tenant_member(tenant_id)
  and user_id = auth.uid()
);

create policy "tenant_evolution_connections_update_own"
on public.tenant_evolution_connections
for update to authenticated
using (
  public.is_tenant_member(tenant_id)
  and user_id = auth.uid()
)
with check (
  public.is_tenant_member(tenant_id)
  and user_id = auth.uid()
);

create policy "tenant_evolution_connections_delete_own"
on public.tenant_evolution_connections
for delete to authenticated
using (
  public.is_tenant_member(tenant_id)
  and user_id = auth.uid()
);
