alter table public.eventos
  add column if not exists fechamento_confirmado_em timestamptz;

create table public.tenant_closing_form_fields (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  section text not null,
  label text not null,
  field_key text,
  field_type text not null default 'text',
  required boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0,
  is_system boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_closing_form_fields_label_check check (char_length(trim(label)) > 0),
  constraint tenant_closing_form_fields_section_check check (
    section in ('cliente', 'aniversariante', 'festa', 'financeiro', 'contrato')
  ),
  constraint tenant_closing_form_fields_type_check check (
    field_type in ('text', 'email', 'phone', 'date', 'time', 'number', 'currency', 'textarea', 'checkbox')
  ),
  constraint tenant_closing_form_fields_key_unique unique (tenant_id, field_key)
);

create table public.evento_closing_responses (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  evento_id bigint not null,
  field_id bigint not null,
  value text,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint evento_closing_responses_evento_tenant_fkey
    foreign key (evento_id, tenant_id)
    references public.eventos(id, tenant_id)
    on delete cascade,
  constraint evento_closing_responses_field_tenant_fkey
    foreign key (field_id, tenant_id)
    references public.tenant_closing_form_fields(id, tenant_id)
    on delete cascade,
  constraint evento_closing_responses_unique unique (evento_id, field_id)
);

alter table public.tenant_closing_form_fields
  add constraint tenant_closing_form_fields_id_tenant_id_key unique (id, tenant_id);

create index tenant_closing_form_fields_tenant_idx
  on public.tenant_closing_form_fields (tenant_id, section, sort_order);
create index evento_closing_responses_tenant_evento_idx
  on public.evento_closing_responses (tenant_id, evento_id);

create trigger set_tenant_closing_form_fields_updated_at
before update on public.tenant_closing_form_fields
for each row execute function public.set_updated_at();

create trigger set_evento_closing_responses_updated_at
before update on public.evento_closing_responses
for each row execute function public.set_updated_at();

alter table public.tenant_closing_form_fields enable row level security;
alter table public.evento_closing_responses enable row level security;

create policy "tenant_closing_form_fields_members_all"
on public.tenant_closing_form_fields
for all to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

create policy "evento_closing_responses_select_members"
on public.evento_closing_responses
for select to authenticated
using (public.is_tenant_member(tenant_id));

create policy "evento_closing_responses_insert_members"
on public.evento_closing_responses
for insert to authenticated
with check (public.is_tenant_member(tenant_id));

create policy "evento_closing_responses_update_members"
on public.evento_closing_responses
for update to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

create policy "evento_closing_responses_delete_members"
on public.evento_closing_responses
for delete to authenticated
using (public.is_tenant_member(tenant_id));

-- Seed default closing form fields for all existing tenants
insert into public.tenant_closing_form_fields (
  tenant_id, section, label, field_key, field_type, required, active, sort_order, is_system
)
select
  t.id,
  seed.section,
  seed.label,
  seed.field_key,
  seed.field_type,
  seed.required,
  true,
  seed.sort_order,
  true
from public.tenants t
cross join (
  values
    ('cliente', 'Nome do responsável', 'cliente_nome', 'text', true, 1),
    ('cliente', 'Telefone', 'cliente_telefone', 'phone', true, 2),
    ('cliente', 'E-mail', 'cliente_email', 'email', false, 3),
    ('aniversariante', 'Nome do aniversariante', 'aniversariante_nome', 'text', true, 1),
    ('aniversariante', 'Data de nascimento', 'aniversariante_data_nascimento', 'date', true, 2),
    ('festa', 'Data da festa', 'data_evento', 'date', true, 1),
    ('festa', 'Horário', 'hora_evento', 'time', true, 2),
    ('festa', 'Quantidade de convidados', 'quantidade_convidados', 'number', true, 3),
    ('festa', 'Pacote contratado', 'pacote_nome', 'text', true, 4),
    ('financeiro', 'Valor do pacote', 'valor_pacote', 'currency', true, 1),
    ('financeiro', 'Valor dos adicionais', 'valor_adicionais', 'currency', false, 2),
    ('financeiro', 'Valor total', 'valor_total', 'currency', true, 3),
    ('financeiro', 'Valor da entrada', 'valor_entrada', 'currency', true, 4),
    ('contrato', 'Observações do contrato', 'observacoes', 'textarea', false, 1)
) as seed(section, label, field_key, field_type, required, sort_order)
on conflict (tenant_id, field_key) do nothing;

create or replace function public.seed_tenant_closing_form_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.tenant_closing_form_fields (
    tenant_id, section, label, field_key, field_type, required, active, sort_order, is_system
  )
  values
    (new.id, 'cliente', 'Nome do responsável', 'cliente_nome', 'text', true, true, 1, true),
    (new.id, 'cliente', 'Telefone', 'cliente_telefone', 'phone', true, true, 2, true),
    (new.id, 'cliente', 'E-mail', 'cliente_email', 'email', false, true, 3, true),
    (new.id, 'aniversariante', 'Nome do aniversariante', 'aniversariante_nome', 'text', true, true, 1, true),
    (new.id, 'aniversariante', 'Data de nascimento', 'aniversariante_data_nascimento', 'date', true, true, 2, true),
    (new.id, 'festa', 'Data da festa', 'data_evento', 'date', true, true, 1, true),
    (new.id, 'festa', 'Horário', 'hora_evento', 'time', true, true, 2, true),
    (new.id, 'festa', 'Quantidade de convidados', 'quantidade_convidados', 'number', true, true, 3, true),
    (new.id, 'festa', 'Pacote contratado', 'pacote_nome', 'text', true, true, 4, true),
    (new.id, 'financeiro', 'Valor do pacote', 'valor_pacote', 'currency', true, true, 1, true),
    (new.id, 'financeiro', 'Valor dos adicionais', 'valor_adicionais', 'currency', false, true, 2, true),
    (new.id, 'financeiro', 'Valor total', 'valor_total', 'currency', true, true, 3, true),
    (new.id, 'financeiro', 'Valor da entrada', 'valor_entrada', 'currency', true, true, 4, true),
    (new.id, 'contrato', 'Observações do contrato', 'observacoes', 'textarea', false, true, 1, true)
  on conflict (tenant_id, field_key) do nothing;

  return new;
end;
$$;

create trigger seed_closing_form_on_tenant_create
after insert on public.tenants
for each row
execute function public.seed_tenant_closing_form_fields();
