-- Matriz e filiais dentro do mesmo tenant.
-- O login, os membros e a assinatura continuam no tenant.
-- A casa (unidade) passa a ser o escopo de cadastro, operação, configuração e WhatsApp.

create table public.tenant_units (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants (id) on delete cascade,
  kind text not null,
  parent_unit_id bigint references public.tenant_units (id) on delete restrict,
  name text not null,
  slug text not null,
  document text,
  phone text,
  email text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_units_kind_check check (kind in ('matriz', 'filial')),
  constraint tenant_units_status_check check (status in ('active', 'inactive')),
  constraint tenant_units_slug_format_check check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint tenant_units_name_check check (char_length(btrim(name)) > 0),
  constraint tenant_units_tenant_slug_unique unique (tenant_id, slug)
);

create unique index tenant_units_one_matriz_idx
  on public.tenant_units (tenant_id)
  where kind = 'matriz';

create index tenant_units_tenant_id_idx on public.tenant_units (tenant_id);

create trigger set_tenant_units_updated_at
before update on public.tenant_units
for each row execute function public.set_updated_at();

comment on table public.tenant_units is
  'Casas do tenant. Uma matriz e zero ou mais filiais. O acesso continua sendo o do tenant.';

create or replace function public.tenant_matriz_unit_id(p_tenant_id bigint)
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select id
  from public.tenant_units
  where tenant_id = p_tenant_id
    and kind = 'matriz'
  limit 1;
$$;

create or replace function public.enforce_tenant_unit_shape()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_parent public.tenant_units%rowtype;
begin
  if new.kind = 'matriz' then
    if new.parent_unit_id is not null then
      raise exception 'A matriz não referencia outra unidade.';
    end if;
    return new;
  end if;

  if new.parent_unit_id is null then
    raise exception 'A filial precisa apontar para a matriz do tenant.';
  end if;

  select * into v_parent
  from public.tenant_units
  where id = new.parent_unit_id;

  if v_parent.id is null or v_parent.tenant_id <> new.tenant_id or v_parent.kind <> 'matriz' then
    raise exception 'A filial só pode referenciar a matriz do mesmo tenant.';
  end if;

  return new;
end;
$$;

create trigger enforce_tenant_unit_shape
before insert or update on public.tenant_units
for each row execute function public.enforce_tenant_unit_shape();

create or replace function public.ensure_tenant_matriz_unit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.tenant_units (tenant_id, kind, name, slug, document, phone, email, status)
  values (
    new.id,
    'matriz',
    new.name,
    new.slug,
    new.document,
    new.phone,
    new.email,
    'active'
  )
  on conflict (tenant_id, slug) do nothing;

  return new;
end;
$$;

-- Nome começa com "a_" para rodar antes dos seeds do tenant.
create trigger a_ensure_tenant_matriz_unit
after insert on public.tenants
for each row execute function public.ensure_tenant_matriz_unit();

insert into public.tenant_units (tenant_id, kind, name, slug, document, phone, email, status)
select
  t.id,
  'matriz',
  t.name,
  t.slug,
  t.document,
  t.phone,
  t.email,
  'active'
from public.tenants t
on conflict (tenant_id, slug) do nothing;

alter table public.tenant_units enable row level security;

create policy tenant_units_select_member
on public.tenant_units
for select
to authenticated
using (public.is_tenant_member(tenant_id) or public.is_platform_admin());

create policy tenant_units_insert_admin
on public.tenant_units
for insert
to authenticated
with check (
  kind = 'filial'
  and (public.has_tenant_role(tenant_id, array['owner', 'admin']) or public.is_platform_admin())
);

create policy tenant_units_update_admin
on public.tenant_units
for update
to authenticated
using (public.has_tenant_role(tenant_id, array['owner', 'admin']) or public.is_platform_admin())
with check (public.has_tenant_role(tenant_id, array['owner', 'admin']) or public.is_platform_admin());

-- Cabeçalho do app: x-festaai-unit-id e x-festaai-unit-scope (one | all).
create or replace function public.request_header(p_name text)
returns text
language plpgsql
stable
as $$
declare
  v_headers json;
begin
  begin
    v_headers := current_setting('request.headers', true)::json;
  exception
    when others then
      return null;
  end;

  return nullif(v_headers->>p_name, '');
end;
$$;

create or replace function public.can_read_tenant_unit(
  p_tenant_id bigint,
  p_unit_id bigint,
  p_mode text
)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_requested bigint;
  v_scope text;
  v_header text;
begin
  if p_unit_id is null then
    return public.is_platform_admin();
  end if;

  if not (public.is_tenant_member(p_tenant_id) or public.is_platform_admin()) then
    return false;
  end if;

  if not exists (
    select 1
    from public.tenant_units u
    where u.id = p_unit_id
      and u.tenant_id = p_tenant_id
  ) then
    return false;
  end if;

  v_scope := coalesce(public.request_header('x-festaai-unit-scope'), 'one');
  v_header := public.request_header('x-festaai-unit-id');

  begin
    v_requested := v_header::bigint;
  exception
    when others then
      v_requested := null;
  end;

  if p_mode = 'operational' and v_scope = 'all' then
    return true;
  end if;

  if v_requested is not null and exists (
    select 1
    from public.tenant_units u
    where u.id = v_requested
      and u.tenant_id = p_tenant_id
  ) then
    return p_unit_id = v_requested;
  end if;

  return p_unit_id = public.tenant_matriz_unit_id(p_tenant_id);
end;
$$;

create or replace function public.can_write_tenant_unit(p_tenant_id bigint, p_unit_id bigint)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_requested bigint;
  v_header text;
begin
  if p_unit_id is null then
    return public.is_platform_admin();
  end if;

  if not (public.is_tenant_member(p_tenant_id) or public.is_platform_admin()) then
    return false;
  end if;

  if not exists (
    select 1
    from public.tenant_units u
    where u.id = p_unit_id
      and u.tenant_id = p_tenant_id
  ) then
    return false;
  end if;

  v_header := public.request_header('x-festaai-unit-id');
  begin
    v_requested := v_header::bigint;
  exception
    when others then
      v_requested := null;
  end;

  if v_requested is not null and exists (
    select 1
    from public.tenant_units u
    where u.id = v_requested
      and u.tenant_id = p_tenant_id
  ) then
    return p_unit_id = v_requested;
  end if;

  return p_unit_id = public.tenant_matriz_unit_id(p_tenant_id);
end;
$$;

create or replace function public.assign_tenant_unit_id()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_requested bigint;
  v_header text;
begin
  if new.tenant_id is null then
    if new.unit_id is not null then
      raise exception 'unit_id exige tenant_id';
    end if;
    return new;
  end if;

  if new.unit_id is not null then
    if not exists (
      select 1
      from public.tenant_units u
      where u.id = new.unit_id
        and u.tenant_id = new.tenant_id
    ) then
      raise exception 'A unidade % não pertence ao tenant %', new.unit_id, new.tenant_id;
    end if;
    return new;
  end if;

  v_header := public.request_header('x-festaai-unit-id');
  begin
    v_requested := v_header::bigint;
  exception
    when others then
      v_requested := null;
  end;

  if v_requested is not null and exists (
    select 1
    from public.tenant_units u
    where u.id = v_requested
      and u.tenant_id = new.tenant_id
  ) then
    new.unit_id := v_requested;
  else
    new.unit_id := public.tenant_matriz_unit_id(new.tenant_id);
  end if;

  if new.unit_id is null then
    raise exception 'O tenant % não tem matriz.', new.tenant_id;
  end if;

  return new;
end;
$$;

-- Tabelas com uma linha por casa: a chave passa a ser unit_id.
do $$
declare
  t text;
begin
  foreach t in array array[
    'tenant_company_profiles',
    'tenant_guided_setup_progress',
    'tenant_estrutura_settings',
    'tenant_financial_settings',
    'tenant_automation_settings',
    'tenant_contract_module_settings'
  ]
  loop
    execute format('alter table public.%I add column if not exists unit_id bigint', t);
    execute format(
      'update public.%I as row set unit_id = u.id from public.tenant_units u where row.tenant_id = u.tenant_id and u.kind = ''matriz'' and row.unit_id is null',
      t
    );
    execute format('alter table public.%I alter column unit_id set not null', t);
    execute format('alter table public.%I drop constraint if exists %I', t, t || '_pkey');
    execute format('alter table public.%I add primary key (unit_id)', t);
    execute format(
      'alter table public.%I drop constraint if exists %I',
      t,
      t || '_unit_id_fkey'
    );
    execute format(
      'alter table public.%I add constraint %I foreign key (unit_id) references public.tenant_units (id) on delete cascade',
      t,
      t || '_unit_id_fkey'
    );
    execute format('create index if not exists %I on public.%I (tenant_id)', t || '_tenant_idx', t);
  end loop;
end $$;

-- Listas operacionais e de configuração.
do $$
declare
  t text;
begin
  foreach t in array array[
    'eventos',
    'calendar_blocks',
    'financeiro_lancamentos',
    'tenant_packages',
    'tenant_additionals',
    'tenant_commercial_plans',
    'tenant_checklist_categories',
    'tenant_checklist_items',
    'tenant_message_templates',
    'tenant_holidays',
    'tenant_payment_methods',
    'tenant_acceptance_terms',
    'tenant_satisfaction_survey_questions',
    'tenant_closing_form_fields',
    'tenant_contract_templates',
    'tenant_contract_module_acceptances',
    'agent_conversation_messages'
  ]
  loop
    execute format('alter table public.%I add column if not exists unit_id bigint', t);
    execute format(
      'update public.%I as row set unit_id = u.id from public.tenant_units u where row.tenant_id = u.tenant_id and u.kind = ''matriz'' and row.unit_id is null',
      t
    );
    execute format('alter table public.%I alter column unit_id set not null', t);
    execute format('alter table public.%I drop constraint if exists %I', t, t || '_unit_id_fkey');
    execute format(
      'alter table public.%I add constraint %I foreign key (unit_id) references public.tenant_units (id) on delete cascade',
      t,
      t || '_unit_id_fkey'
    );
    execute format('create index if not exists %I on public.%I (tenant_id, unit_id)', t || '_tenant_unit_idx', t);
  end loop;
end $$;

alter table public.whatsapp_connections
  add column if not exists unit_id bigint references public.tenant_units (id) on delete cascade;

update public.whatsapp_connections as connection
set unit_id = u.id
from public.tenant_units u
where connection.tenant_id = u.tenant_id
  and u.kind = 'matriz'
  and connection.unit_id is null
  and connection.scope = 'tenant';

alter table public.whatsapp_connections
  drop constraint if exists whatsapp_connections_unit_scope_check;

alter table public.whatsapp_connections
  add constraint whatsapp_connections_unit_scope_check
  check (
    (scope = 'platform' and unit_id is null)
    or (scope = 'tenant' and unit_id is not null)
  );

create index if not exists whatsapp_connections_tenant_unit_idx
  on public.whatsapp_connections (tenant_id, unit_id);

alter table public.automation_dispatch_logs
  add column if not exists unit_id bigint references public.tenant_units (id) on delete set null;

update public.automation_dispatch_logs as log
set unit_id = connection.unit_id
from public.whatsapp_connections as connection
where log.connection_id = connection.id
  and log.unit_id is null;

update public.agent_conversation_messages as message
set unit_id = connection.unit_id
from public.whatsapp_connections as connection
where message.connection_id = connection.id
  and connection.unit_id is not null
  and message.unit_id is distinct from connection.unit_id;

-- Unicidade passa a incluir a casa.
alter table public.calendar_blocks drop constraint if exists calendar_blocks_tenant_data_key;
create unique index if not exists calendar_blocks_unit_data_key on public.calendar_blocks (unit_id, data);

alter table public.tenant_message_templates drop constraint if exists tenant_message_templates_key_unique;
create unique index if not exists tenant_message_templates_unit_key_unique on public.tenant_message_templates (unit_id, key);

alter table public.tenant_payment_methods drop constraint if exists tenant_payment_methods_tenant_name_unique;
create unique index if not exists tenant_payment_methods_unit_name_unique on public.tenant_payment_methods (unit_id, name);

alter table public.tenant_acceptance_terms drop constraint if exists tenant_acceptance_terms_key_unique;
create unique index if not exists tenant_acceptance_terms_unit_key_unique on public.tenant_acceptance_terms (unit_id, term_key);

alter table public.tenant_satisfaction_survey_questions drop constraint if exists tenant_satisfaction_survey_questions_key_unique;
create unique index if not exists tenant_satisfaction_survey_questions_unit_key_unique
  on public.tenant_satisfaction_survey_questions (unit_id, question_key);

alter table public.tenant_closing_form_fields drop constraint if exists tenant_closing_form_fields_key_unique;
create unique index if not exists tenant_closing_form_fields_unit_key_unique
  on public.tenant_closing_form_fields (unit_id, field_key);

alter table public.tenant_contract_module_acceptances
  drop constraint if exists tenant_contract_module_acceptances_tenant_version_unique;
create unique index if not exists tenant_contract_module_acceptances_unit_version_unique
  on public.tenant_contract_module_acceptances (unit_id, terms_version);

drop index if exists public.tenant_packages_tenant_name_automacao_key;
create unique index if not exists tenant_packages_unit_name_automacao_key
  on public.tenant_packages (unit_id, name_automacao);

drop index if exists public.tenant_contract_templates_tenant_key_idx;
create unique index if not exists tenant_contract_templates_unit_key_idx
  on public.tenant_contract_templates (unit_id, template_key);

drop index if exists public.tenant_holidays_unique_one_shot;
create unique index tenant_holidays_unique_one_shot
  on public.tenant_holidays (unit_id, holiday_date, scope, kind, lower(btrim(name)))
  where not recurs_annually;

drop index if exists public.tenant_holidays_unique_recurring_md;
create unique index tenant_holidays_unique_recurring_md
  on public.tenant_holidays (
    unit_id,
    public.date_month(holiday_date),
    public.date_day(holiday_date),
    scope,
    kind,
    lower(btrim(name))
  )
  where recurs_annually;

do $$
declare
  t text;
  v_mode text;
begin
  foreach t in array array[
    'eventos',
    'calendar_blocks',
    'financeiro_lancamentos',
    'tenant_packages',
    'tenant_additionals',
    'tenant_commercial_plans',
    'tenant_checklist_categories',
    'tenant_checklist_items',
    'tenant_message_templates',
    'tenant_holidays',
    'tenant_payment_methods',
    'tenant_acceptance_terms',
    'tenant_satisfaction_survey_questions',
    'tenant_closing_form_fields',
    'tenant_contract_templates',
    'tenant_contract_module_acceptances',
    'tenant_company_profiles',
    'tenant_guided_setup_progress',
    'tenant_estrutura_settings',
    'tenant_financial_settings',
    'tenant_automation_settings',
    'tenant_contract_module_settings',
    'whatsapp_connections',
    'agent_conversation_messages'
  ]
  loop
    v_mode := case
      when t in ('eventos', 'calendar_blocks', 'financeiro_lancamentos') then 'operational'
      else 'config'
    end;

    execute format('drop trigger if exists assign_tenant_unit_id on public.%I', t);
    execute format(
      'create trigger assign_tenant_unit_id before insert or update on public.%I for each row execute function public.assign_tenant_unit_id()',
      t
    );

    execute format('drop policy if exists tenant_unit_scope on public.%I', t);
    execute format(
      'create policy tenant_unit_scope on public.%I as restrictive for all to authenticated using (public.can_read_tenant_unit(tenant_id, unit_id, %L)) with check (public.can_write_tenant_unit(tenant_id, unit_id))',
      t,
      v_mode
    );
  end loop;
end $$;

-- Filhos do evento seguem a casa do evento.
do $$
declare
  t text;
begin
  foreach t in array array[
    'evento_pagamentos',
    'evento_tarefas',
    'evento_notas',
    'evento_contracts',
    'evento_closing_responses',
    'evento_acceptance_responses',
    'evento_satisfaction_responses'
  ]
  loop
    execute format('drop policy if exists tenant_unit_scope_via_evento on public.%I', t);
    execute format($policy$
      create policy tenant_unit_scope_via_evento
      on public.%I
      as restrictive
      for all
      to authenticated
      using (
        exists (
          select 1
          from public.eventos e
          where e.id = %I.evento_id
            and public.can_read_tenant_unit(e.tenant_id, e.unit_id, 'operational')
        )
      )
      with check (
        exists (
          select 1
          from public.eventos e
          where e.id = %I.evento_id
            and public.can_write_tenant_unit(e.tenant_id, e.unit_id)
        )
      )
    $policy$, t, t, t);
  end loop;
end $$;

-- Seeds de tenant novo passam a respeitar a unicidade por unidade.
do $$
declare
  v_sql text;
  v_signature text;
begin
  foreach v_signature in array array[
    'public.seed_tenant_closing_form_fields()',
    'public.seed_tenant_payment_methods()',
    'public.seed_tenant_acceptance_terms()',
    'public.seed_tenant_satisfaction_survey_questions(bigint)',
    'public.seed_tenant_contract_template()',
    'public.seed_tenant_guided_setup_progress()'
  ]
  loop
    v_sql := pg_get_functiondef(v_signature::regprocedure);
    v_sql := replace(v_sql, 'on conflict (tenant_id, field_key)', 'on conflict (unit_id, field_key)');
    v_sql := replace(v_sql, 'on conflict (tenant_id, name)', 'on conflict (unit_id, name)');
    v_sql := replace(v_sql, 'on conflict (tenant_id, term_key)', 'on conflict (unit_id, term_key)');
    v_sql := replace(v_sql, 'on conflict (tenant_id, question_key)', 'on conflict (unit_id, question_key)');
    v_sql := replace(v_sql, 'on conflict (tenant_id, template_key)', 'on conflict (unit_id, template_key)');
    v_sql := replace(v_sql, 'on conflict (tenant_id) do nothing', 'on conflict (unit_id) do nothing');
    execute v_sql;
  end loop;
end $$;

create or replace function public.create_tenant_filial(
  p_tenant_id bigint,
  p_name text,
  p_slug text
)
returns public.tenant_units
language plpgsql
security definer
set search_path = public
as $$
declare
  v_matriz_id bigint;
  v_unit public.tenant_units%rowtype;
begin
  if not (public.has_tenant_role(p_tenant_id, array['owner', 'admin']) or public.is_platform_admin()) then
    raise exception 'Sem permissão para criar filial.';
  end if;

  v_matriz_id := public.tenant_matriz_unit_id(p_tenant_id);
  if v_matriz_id is null then
    raise exception 'O tenant não tem matriz.';
  end if;

  insert into public.tenant_units (tenant_id, kind, parent_unit_id, name, slug, status)
  values (p_tenant_id, 'filial', v_matriz_id, btrim(p_name), p_slug, 'active')
  returning * into v_unit;

  insert into public.tenant_company_profiles (tenant_id, unit_id, company_name)
  values (p_tenant_id, v_unit.id, btrim(p_name))
  on conflict (unit_id) do nothing;

  insert into public.tenant_guided_setup_progress (tenant_id, unit_id, current_step, completed_steps)
  values (p_tenant_id, v_unit.id, 'company_profile', '{}')
  on conflict (unit_id) do nothing;

  insert into public.tenant_closing_form_fields (
    tenant_id, unit_id, section, label, field_key, field_type, required, active, sort_order, is_system,
    category, is_locked, usage_contract, usage_party_summary, usage_ai, usage_reports, usage_checklist,
    usage_internal_task, description, config, package_ids
  )
  select
    p_tenant_id, v_unit.id, section, label, field_key, field_type, required, active, sort_order, is_system,
    category, is_locked, usage_contract, usage_party_summary, usage_ai, usage_reports, usage_checklist,
    usage_internal_task, description, config, package_ids
  from public.tenant_closing_form_fields
  where unit_id = v_matriz_id
    and is_system = true
  on conflict (unit_id, field_key) do nothing;

  insert into public.tenant_payment_methods (
    tenant_id, unit_id, name, payment_type, allows_installments, max_installments,
    allowed_for_deposit, allowed_for_remaining_balance, active, sort_order
  )
  select
    p_tenant_id, v_unit.id, name, payment_type, allows_installments, max_installments,
    allowed_for_deposit, allowed_for_remaining_balance, active, sort_order
  from public.tenant_payment_methods
  where unit_id = v_matriz_id
  on conflict (unit_id, name) do nothing;

  insert into public.tenant_acceptance_terms (
    tenant_id, unit_id, term_key, title, content, is_required, appears_in_contract,
    is_system, active, sort_order, show_in_form, show_at_signing
  )
  select
    p_tenant_id, v_unit.id, term_key, title, content, is_required, appears_in_contract,
    is_system, active, sort_order, show_in_form, show_at_signing
  from public.tenant_acceptance_terms
  where unit_id = v_matriz_id
    and is_system = true
  on conflict (unit_id, term_key) do nothing;

  insert into public.tenant_satisfaction_survey_questions (
    tenant_id, unit_id, label, question_key, question_type, required, active, sort_order, config, is_system
  )
  select
    p_tenant_id, v_unit.id, label, question_key, question_type, required, active, sort_order, config, is_system
  from public.tenant_satisfaction_survey_questions
  where unit_id = v_matriz_id
    and is_system = true
  on conflict (unit_id, question_key) do nothing;

  return v_unit;
end;
$$;

revoke all on function public.create_tenant_filial(bigint, text, text) from public;
grant execute on function public.create_tenant_filial(bigint, text, text) to authenticated;

revoke all on function public.can_read_tenant_unit(bigint, bigint, text) from public;
grant execute on function public.can_read_tenant_unit(bigint, bigint, text) to authenticated;

revoke all on function public.can_write_tenant_unit(bigint, bigint) from public;
grant execute on function public.can_write_tenant_unit(bigint, bigint) to authenticated;

revoke all on function public.tenant_matriz_unit_id(bigint) from public;
grant execute on function public.tenant_matriz_unit_id(bigint) to authenticated;
