-- Leads do card "Plano sob medida" e ofertas comerciais privadas (propostas FestaAI).

create table public.commercial_leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  company_name text not null,
  message text not null default '',
  status text not null default 'novo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commercial_leads_status_check check (
    status in ('novo', 'em_contato', 'convertido', 'descartado')
  )
);

create table public.commercial_offers (
  id bigint generated by default as identity primary key,
  token text not null unique,
  name text not null,
  base_plan_slug text not null,
  monthly_price numeric(12, 2) not null,
  setup_price numeric(12, 2) not null default 0,
  setup_installments integer,
  loyalty_months integer,
  recipient_company text,
  recipient_email text,
  status text not null default 'draft',
  expires_at timestamptz not null,
  lead_id bigint references public.commercial_leads (id) on delete set null,
  billing_subscription_id bigint references public.billing_subscriptions (id) on delete set null,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commercial_offers_base_plan_slug_check check (
    base_plan_slug in ('avista', 'parcelado', 'fidelidade')
  ),
  constraint commercial_offers_status_check check (
    status in ('draft', 'active', 'accepted', 'expired', 'cancelled')
  ),
  constraint commercial_offers_values_check check (
    monthly_price >= 0
    and setup_price >= 0
    and (setup_installments is null or setup_installments > 0)
    and (loyalty_months is null or loyalty_months >= 0)
  )
);

create index commercial_leads_status_created_idx on public.commercial_leads (status, created_at desc);
create index commercial_offers_status_expires_idx on public.commercial_offers (status, expires_at desc);
create index commercial_offers_token_idx on public.commercial_offers (token);

create trigger set_commercial_leads_updated_at
before update on public.commercial_leads
for each row execute function public.set_updated_at();

create trigger set_commercial_offers_updated_at
before update on public.commercial_offers
for each row execute function public.set_updated_at();

alter table public.commercial_leads enable row level security;
alter table public.commercial_offers enable row level security;

-- Platform admin: gestão completa de leads e ofertas.
create policy "commercial_leads_select_platform_admin"
on public.commercial_leads for select to authenticated
using (public.is_platform_admin());

create policy "commercial_leads_insert_platform_admin"
on public.commercial_leads for insert to authenticated
with check (public.is_platform_admin());

create policy "commercial_leads_update_platform_admin"
on public.commercial_leads for update to authenticated
using (public.is_platform_admin())
with check (public.is_platform_admin());

create policy "commercial_offers_select_platform_admin"
on public.commercial_offers for select to authenticated
using (public.is_platform_admin());

create policy "commercial_offers_insert_platform_admin"
on public.commercial_offers for insert to authenticated
with check (public.is_platform_admin());

create policy "commercial_offers_update_platform_admin"
on public.commercial_offers for update to authenticated
using (public.is_platform_admin())
with check (public.is_platform_admin());

-- Leitura pública de oferta ativa por token (via RPC security definer abaixo).

create or replace function public.get_public_commercial_offer(p_token text)
returns table (
  id bigint,
  token text,
  name text,
  base_plan_slug text,
  monthly_price numeric,
  setup_price numeric,
  setup_installments integer,
  loyalty_months integer,
  recipient_company text,
  recipient_email text,
  expires_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    o.id,
    o.token,
    o.name,
    o.base_plan_slug,
    o.monthly_price,
    o.setup_price,
    o.setup_installments,
    o.loyalty_months,
    o.recipient_company,
    o.recipient_email,
    o.expires_at
  from public.commercial_offers o
  where o.token = p_token
    and o.status = 'active'
    and o.expires_at > now()
  limit 1;
$$;

revoke all on function public.get_public_commercial_offer(text) from public;
grant execute on function public.get_public_commercial_offer(text) to anon, authenticated;

comment on table public.commercial_leads is 'Leads capturados pelo card Plano sob medida na página /contratar.';
comment on table public.commercial_offers is 'Propostas comerciais privadas com link exclusivo para formalização.';
