-- Fase A: expandir configuração do formulário de contratação (metadados, seed, aceites, pagamentos)

-- ---------------------------------------------------------------------------
-- 0. Reparo idempotente — garante tabelas base caso o remoto esteja inconsistente
-- ---------------------------------------------------------------------------

alter table public.eventos
  add column if not exists fechamento_confirmado_em timestamptz;

create table if not exists public.tenant_closing_form_fields (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  section text not null,
  label text not null,
  field_key text,
  field_type text not null default 'text',
  required boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0,
  is_system boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_closing_form_fields_label_check check (char_length(trim(label)) > 0),
  constraint tenant_closing_form_fields_section_check check (
    section in ('cliente', 'aniversariante', 'festa', 'financeiro', 'contrato')
  ),
  constraint tenant_closing_form_fields_type_check check (
    field_type in ('text', 'email', 'phone', 'date', 'time', 'number', 'currency', 'textarea', 'checkbox')
  ),
  constraint tenant_closing_form_fields_key_unique unique (tenant_id, field_key)
);

create table if not exists public.evento_closing_responses (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  evento_id bigint not null,
  field_id bigint not null,
  value text,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint evento_closing_responses_unique unique (evento_id, field_id)
);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'tenant_closing_form_fields_id_tenant_id_key'
  ) then
    alter table public.tenant_closing_form_fields
      add constraint tenant_closing_form_fields_id_tenant_id_key unique (id, tenant_id);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'evento_closing_responses_evento_tenant_fkey'
  ) then
    alter table public.evento_closing_responses
      add constraint evento_closing_responses_evento_tenant_fkey
        foreign key (evento_id, tenant_id)
        references public.eventos(id, tenant_id)
        on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'evento_closing_responses_field_tenant_fkey'
  ) then
    alter table public.evento_closing_responses
      add constraint evento_closing_responses_field_tenant_fkey
        foreign key (field_id, tenant_id)
        references public.tenant_closing_form_fields(id, tenant_id)
        on delete cascade;
  end if;
end $$;

create index if not exists tenant_closing_form_fields_tenant_idx
  on public.tenant_closing_form_fields (tenant_id, section, sort_order);
create index if not exists evento_closing_responses_tenant_evento_idx
  on public.evento_closing_responses (tenant_id, evento_id);

drop trigger if exists set_tenant_closing_form_fields_updated_at on public.tenant_closing_form_fields;
create trigger set_tenant_closing_form_fields_updated_at
before update on public.tenant_closing_form_fields
for each row execute function public.set_updated_at();

drop trigger if exists set_evento_closing_responses_updated_at on public.evento_closing_responses;
create trigger set_evento_closing_responses_updated_at
before update on public.evento_closing_responses
for each row execute function public.set_updated_at();

alter table public.tenant_closing_form_fields enable row level security;
alter table public.evento_closing_responses enable row level security;

drop policy if exists "tenant_closing_form_fields_members_all" on public.tenant_closing_form_fields;
create policy "tenant_closing_form_fields_members_all"
on public.tenant_closing_form_fields
for all to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

drop policy if exists "evento_closing_responses_select_members" on public.evento_closing_responses;
create policy "evento_closing_responses_select_members"
on public.evento_closing_responses
for select to authenticated
using (public.is_tenant_member(tenant_id));

drop policy if exists "evento_closing_responses_insert_members" on public.evento_closing_responses;
create policy "evento_closing_responses_insert_members"
on public.evento_closing_responses
for insert to authenticated
with check (public.is_tenant_member(tenant_id));

drop policy if exists "evento_closing_responses_update_members" on public.evento_closing_responses;
create policy "evento_closing_responses_update_members"
on public.evento_closing_responses
for update to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

drop policy if exists "evento_closing_responses_delete_members" on public.evento_closing_responses;
create policy "evento_closing_responses_delete_members"
on public.evento_closing_responses
for delete to authenticated
using (public.is_tenant_member(tenant_id));

-- Seed mínimo dos 14 campos originais (tenants sem registro)
insert into public.tenant_closing_form_fields (
  tenant_id, section, label, field_key, field_type, required, active, sort_order, is_system
)
select
  t.id,
  seed.section,
  seed.label,
  seed.field_key,
  seed.field_type,
  seed.required,
  true,
  seed.sort_order,
  true
from public.tenants t
cross join (
  values
    ('cliente', 'Nome do responsável', 'cliente_nome', 'text', true, 1),
    ('cliente', 'Telefone', 'cliente_telefone', 'phone', true, 2),
    ('cliente', 'E-mail', 'cliente_email', 'email', false, 3),
    ('aniversariante', 'Nome do aniversariante', 'aniversariante_nome', 'text', true, 1),
    ('aniversariante', 'Data de nascimento', 'aniversariante_data_nascimento', 'date', true, 2),
    ('festa', 'Data da festa', 'data_evento', 'date', true, 1),
    ('festa', 'Horário', 'hora_evento', 'time', true, 2),
    ('festa', 'Quantidade de convidados', 'quantidade_convidados', 'number', true, 3),
    ('festa', 'Pacote contratado', 'pacote_nome', 'text', true, 4),
    ('financeiro', 'Valor do pacote', 'valor_pacote', 'currency', true, 1),
    ('financeiro', 'Valor dos adicionais', 'valor_adicionais', 'currency', false, 2),
    ('financeiro', 'Valor total', 'valor_total', 'currency', true, 3),
    ('financeiro', 'Valor da entrada', 'valor_entrada', 'currency', true, 4),
    ('contrato', 'Observações do contrato', 'observacoes', 'textarea', false, 1)
) as seed(section, label, field_key, field_type, required, sort_order)
on conflict (tenant_id, field_key) do nothing;

-- ---------------------------------------------------------------------------
-- 1. tenant_closing_form_fields — metadados e novos tipos/seções
-- ---------------------------------------------------------------------------

alter table public.tenant_closing_form_fields
  add column if not exists description text,
  add column if not exists category text not null default 'operacional',
  add column if not exists is_locked boolean not null default false,
  add column if not exists usage_contract boolean not null default false,
  add column if not exists usage_party_summary boolean not null default false,
  add column if not exists usage_internal_task boolean not null default false,
  add column if not exists usage_ai boolean not null default false,
  add column if not exists usage_checklist boolean not null default false,
  add column if not exists usage_reports boolean not null default false,
  add column if not exists config jsonb not null default '{}'::jsonb;

alter table public.tenant_closing_form_fields
  drop constraint if exists tenant_closing_form_fields_section_check;

-- Renomear seção legada financeiro → pagamento (antes do novo CHECK)
update public.tenant_closing_form_fields
set section = 'pagamento'
where section = 'financeiro';

alter table public.tenant_closing_form_fields
  add constraint tenant_closing_form_fields_section_check check (
    section in (
      'cliente',
      'aniversariante',
      'festa',
      'pacote',
      'adicionais',
      'pagamento',
      'aceites',
      'contrato'
    )
  );

alter table public.tenant_closing_form_fields
  drop constraint if exists tenant_closing_form_fields_type_check;

alter table public.tenant_closing_form_fields
  add constraint tenant_closing_form_fields_type_check check (
    field_type in (
      'text',
      'email',
      'phone',
      'date',
      'time',
      'number',
      'currency',
      'textarea',
      'checkbox',
      'select',
      'multiselect',
      'file',
      'acceptance'
    )
  );

alter table public.tenant_closing_form_fields
  drop constraint if exists tenant_closing_form_fields_category_check;

alter table public.tenant_closing_form_fields
  add constraint tenant_closing_form_fields_category_check check (
    category in ('contratual', 'operacional', 'financeiro', 'comercial', 'experiencia', 'interno')
  );

-- Metadados dos campos sistema existentes
update public.tenant_closing_form_fields set
  label = 'Nome completo',
  category = 'contratual',
  is_locked = true,
  usage_contract = true,
  usage_party_summary = true,
  usage_ai = true,
  usage_reports = true
where field_key = 'cliente_nome';

update public.tenant_closing_form_fields set
  category = 'contratual',
  is_locked = true,
  usage_contract = true,
  usage_party_summary = true,
  usage_ai = true
where field_key = 'cliente_telefone';

update public.tenant_closing_form_fields set
  category = 'contratual',
  usage_contract = true,
  usage_ai = true
where field_key = 'cliente_email';

update public.tenant_closing_form_fields set
  category = 'operacional',
  is_locked = true,
  usage_party_summary = true,
  usage_ai = true,
  usage_checklist = true,
  usage_reports = true
where field_key = 'aniversariante_nome';

update public.tenant_closing_form_fields set
  category = 'operacional',
  is_locked = true,
  usage_party_summary = true,
  usage_ai = true
where field_key = 'aniversariante_data_nascimento';

update public.tenant_closing_form_fields set
  label = 'Horário de início',
  category = 'operacional',
  is_locked = true,
  usage_contract = true,
  usage_party_summary = true,
  usage_ai = true,
  usage_checklist = true
where field_key = 'hora_evento';

update public.tenant_closing_form_fields set
  category = 'operacional',
  is_locked = true,
  usage_party_summary = true,
  usage_ai = true,
  usage_checklist = true,
  usage_reports = true
where field_key = 'data_evento';

update public.tenant_closing_form_fields set
  category = 'operacional',
  is_locked = true,
  usage_party_summary = true,
  usage_ai = true,
  usage_reports = true
where field_key = 'quantidade_convidados';

update public.tenant_closing_form_fields set
  section = 'pacote',
  label = 'Pacote escolhido',
  category = 'comercial',
  is_locked = true,
  usage_contract = true,
  usage_party_summary = true,
  usage_ai = true,
  usage_reports = true
where field_key = 'pacote_nome';

update public.tenant_closing_form_fields set
  section = 'pacote',
  category = 'financeiro',
  is_locked = true,
  usage_contract = true,
  usage_reports = true
where field_key = 'valor_pacote';

update public.tenant_closing_form_fields set
  section = 'adicionais',
  category = 'financeiro',
  usage_contract = true,
  usage_reports = true
where field_key = 'valor_adicionais';

update public.tenant_closing_form_fields set
  section = 'pagamento',
  category = 'financeiro',
  is_locked = true,
  usage_contract = true,
  usage_reports = true
where field_key = 'valor_total';

update public.tenant_closing_form_fields set
  section = 'pagamento',
  category = 'financeiro',
  is_locked = true,
  usage_contract = true,
  usage_reports = true
where field_key = 'valor_entrada';

update public.tenant_closing_form_fields set
  section = 'contrato',
  category = 'contratual',
  usage_contract = true
where field_key = 'observacoes';

-- Novos campos sistema (seed para tenants existentes)
insert into public.tenant_closing_form_fields (
  tenant_id, section, label, field_key, field_type, required, active, sort_order, is_system,
  category, is_locked, usage_contract, usage_party_summary, usage_internal_task,
  usage_ai, usage_checklist, usage_reports, description
)
select
  t.id,
  seed.section,
  seed.label,
  seed.field_key,
  seed.field_type,
  seed.required,
  true,
  seed.sort_order,
  true,
  seed.category,
  seed.is_locked,
  seed.usage_contract,
  seed.usage_party_summary,
  seed.usage_internal_task,
  seed.usage_ai,
  seed.usage_checklist,
  seed.usage_reports,
  seed.description
from public.tenants t
cross join (
  values
    ('cliente', 'CPF', 'cliente_cpf', 'text', true, 4, 'contratual', true, true, true, false, true, false, true, 'Documento do responsável pela contratação'),
    ('cliente', 'RG', 'cliente_rg', 'text', false, 5, 'contratual', false, true, false, false, false, false, false, null),
    ('cliente', 'CEP', 'cliente_cep', 'text', true, 6, 'contratual', false, true, true, false, false, false, false, null),
    ('cliente', 'Rua', 'cliente_rua', 'text', true, 7, 'contratual', false, true, true, false, false, false, false, null),
    ('cliente', 'Número', 'cliente_numero', 'text', true, 8, 'contratual', false, true, true, false, false, false, false, null),
    ('cliente', 'Bairro', 'cliente_bairro', 'text', true, 9, 'contratual', false, true, true, false, false, false, false, null),
    ('cliente', 'Cidade', 'cliente_cidade', 'text', true, 10, 'contratual', false, true, true, false, false, false, false, null),
    ('cliente', 'Estado', 'cliente_estado', 'text', true, 11, 'contratual', false, true, true, false, false, false, false, null),
    ('aniversariante', 'Idade que irá completar', 'aniversariante_idade', 'number', true, 3, 'operacional', false, false, true, false, true, true, true, null),
    ('aniversariante', 'Tema da festa', 'aniversariante_tema', 'text', true, 4, 'experiencia', false, false, true, true, true, true, false, null),
    ('aniversariante', 'Personagem favorito', 'aniversariante_personagem', 'text', false, 5, 'experiencia', false, false, true, false, true, false, false, null),
    ('festa', 'Horário de término', 'hora_termino', 'time', true, 3, 'operacional', true, true, true, false, true, true, false, null),
    ('festa', 'Número de adultos', 'quantidade_adultos', 'number', false, 5, 'operacional', false, false, true, false, true, true, true, null),
    ('festa', 'Número de crianças', 'quantidade_crianas', 'number', false, 6, 'operacional', false, false, true, false, true, true, true, null),
    ('festa', 'Observações gerais', 'observacoes_festa', 'textarea', false, 7, 'operacional', false, false, true, true, true, true, false, null),
    ('pacote', 'Convidados inclusos no pacote', 'pacote_convidados_inclusos', 'number', true, 2, 'comercial', false, true, true, false, true, false, true, null),
    ('pacote', 'Itens inclusos', 'pacote_itens_inclusos', 'textarea', false, 3, 'comercial', false, true, true, false, true, false, false, 'Preenchido automaticamente ao selecionar o pacote'),
    ('pacote', 'Itens não inclusos', 'pacote_itens_nao_inclusos', 'textarea', false, 4, 'comercial', false, true, true, false, true, false, false, 'Preenchido automaticamente ao selecionar o pacote'),
    ('adicionais', 'Adicionais contratados', 'adicionais_selecionados', 'multiselect', false, 1, 'comercial', false, true, true, false, true, true, true, 'Seleção a partir do catálogo de adicionais'),
    ('pagamento', 'Forma de pagamento da entrada', 'forma_pagamento_entrada', 'select', true, 5, 'financeiro', false, true, false, false, false, false, true, null),
    ('pagamento', 'Saldo restante', 'valor_saldo', 'currency', true, 6, 'financeiro', false, true, true, false, false, false, true, 'Calculado automaticamente'),
    ('pagamento', 'Forma de pagamento do saldo', 'forma_pagamento_saldo', 'select', true, 7, 'financeiro', false, true, true, false, false, false, true, null),
    ('pagamento', 'Parcelamento', 'parcelas', 'number', false, 8, 'financeiro', false, false, true, false, false, false, true, null),
    ('pagamento', 'Data limite de pagamento', 'data_limite_pagamento', 'date', false, 9, 'financeiro', false, true, true, false, false, false, true, null)
) as seed(
  section, label, field_key, field_type, required, sort_order, category, is_locked,
  usage_contract, usage_party_summary, usage_internal_task, usage_ai, usage_checklist,
  usage_reports, description
)
on conflict (tenant_id, field_key) do nothing;

-- ---------------------------------------------------------------------------
-- 2. eventos — colunas para campos expandidos (runtime Fase G)
-- ---------------------------------------------------------------------------

alter table public.eventos
  add column if not exists cliente_cpf text,
  add column if not exists cliente_rg text,
  add column if not exists cliente_cep text,
  add column if not exists cliente_rua text,
  add column if not exists cliente_numero text,
  add column if not exists cliente_bairro text,
  add column if not exists cliente_cidade text,
  add column if not exists cliente_estado text,
  add column if not exists aniversariante_idade integer,
  add column if not exists aniversariante_tema text,
  add column if not exists aniversariante_personagem text,
  add column if not exists hora_termino time,
  add column if not exists quantidade_adultos integer,
  add column if not exists quantidade_crianas integer,
  add column if not exists observacoes_festa text,
  add column if not exists pacote_convidados_inclusos integer,
  add column if not exists adicionais_snapshot jsonb,
  add column if not exists forma_pagamento_entrada text,
  add column if not exists forma_pagamento_saldo text,
  add column if not exists valor_saldo numeric(12, 2) not null default 0,
  add column if not exists parcelas integer,
  add column if not exists data_limite_pagamento date;

-- ---------------------------------------------------------------------------
-- 3. tenant_packages — campos expandidos
-- ---------------------------------------------------------------------------

alter table public.tenant_packages
  add column if not exists sort_order integer not null default 0,
  add column if not exists duration_minutes integer,
  add column if not exists included_guests integer,
  add column if not exists included_items jsonb not null default '[]'::jsonb,
  add column if not exists excluded_items jsonb not null default '[]'::jsonb,
  add column if not exists rules text;

create index if not exists tenant_packages_tenant_sort_idx
  on public.tenant_packages (tenant_id, sort_order);

-- ---------------------------------------------------------------------------
-- 4. tenant_additionals — campos expandidos
-- ---------------------------------------------------------------------------

alter table public.tenant_additionals
  add column if not exists description text,
  add column if not exists sort_order integer not null default 0,
  add column if not exists is_required boolean not null default false;

alter table public.tenant_additionals
  drop constraint if exists tenant_additionals_category_check;

alter table public.tenant_additionals
  add constraint tenant_additionals_category_check check (
    category in (
      'buffet',
      'estrutura',
      'equipe',
      'entretenimento',
      'decoracao',
      'brinquedos',
      'fotografia',
      'lembrancinhas',
      'tempo_adicional',
      'outros'
    )
  );

alter table public.tenant_additionals
  drop constraint if exists tenant_additionals_type_check;

alter table public.tenant_additionals
  add constraint tenant_additionals_type_check check (
    type in ('fixo', 'por_unidade', 'por_pessoa', 'por_hora')
  );

create index if not exists tenant_additionals_tenant_sort_idx
  on public.tenant_additionals (tenant_id, sort_order);

-- ---------------------------------------------------------------------------
-- 5. tenant_financial_settings — políticas
-- ---------------------------------------------------------------------------

alter table public.tenant_financial_settings
  add column if not exists cancellation_policy text,
  add column if not exists rescheduling_policy text,
  add column if not exists min_deposit_percentage numeric(5, 2),
  add column if not exists max_deposit_due_days integer,
  add column if not exists max_balance_due_days integer;

-- ---------------------------------------------------------------------------
-- 6. tenant_payment_methods
-- ---------------------------------------------------------------------------

create table public.tenant_payment_methods (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  name text not null,
  payment_type text not null,
  allows_installments boolean not null default false,
  max_installments integer,
  fee_percentage numeric(5, 2),
  fee_fixed numeric(12, 2),
  allowed_for_deposit boolean not null default true,
  allowed_for_remaining_balance boolean not null default true,
  notes text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_payment_methods_name_check check (char_length(trim(name)) > 0),
  constraint tenant_payment_methods_type_check check (
    payment_type in (
      'pix',
      'cartao_credito',
      'cartao_debito',
      'dinheiro',
      'boleto',
      'transferencia',
      'outro'
    )
  ),
  constraint tenant_payment_methods_installments_check check (
    max_installments is null or max_installments >= 1
  ),
  constraint tenant_payment_methods_fees_check check (
    (fee_percentage is null or fee_percentage >= 0)
    and (fee_fixed is null or fee_fixed >= 0)
  ),
  constraint tenant_payment_methods_tenant_name_unique unique (tenant_id, name)
);

create index tenant_payment_methods_tenant_idx
  on public.tenant_payment_methods (tenant_id, active, sort_order);

create trigger set_tenant_payment_methods_updated_at
before update on public.tenant_payment_methods
for each row execute function public.set_updated_at();

alter table public.tenant_payment_methods enable row level security;

create policy "tenant_payment_methods_members_all"
on public.tenant_payment_methods
for all to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

-- ---------------------------------------------------------------------------
-- 7. tenant_acceptance_terms
-- ---------------------------------------------------------------------------

create table public.tenant_acceptance_terms (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  term_key text,
  title text not null,
  content text not null,
  is_required boolean not null default true,
  appears_in_contract boolean not null default true,
  is_system boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_acceptance_terms_title_check check (char_length(trim(title)) > 0),
  constraint tenant_acceptance_terms_content_check check (char_length(trim(content)) > 0),
  constraint tenant_acceptance_terms_key_unique unique (tenant_id, term_key)
);

create index tenant_acceptance_terms_tenant_idx
  on public.tenant_acceptance_terms (tenant_id, active, sort_order);

create trigger set_tenant_acceptance_terms_updated_at
before update on public.tenant_acceptance_terms
for each row execute function public.set_updated_at();

alter table public.tenant_acceptance_terms enable row level security;

create policy "tenant_acceptance_terms_members_all"
on public.tenant_acceptance_terms
for all to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

alter table public.tenant_acceptance_terms
  add constraint tenant_acceptance_terms_id_tenant_id_key unique (id, tenant_id);

-- ---------------------------------------------------------------------------
-- 8. evento_acceptance_responses
-- ---------------------------------------------------------------------------

create table public.evento_acceptance_responses (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  evento_id bigint not null,
  term_id bigint not null,
  accepted boolean not null default false,
  accepted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint evento_acceptance_responses_evento_tenant_fkey
    foreign key (evento_id, tenant_id)
    references public.eventos(id, tenant_id)
    on delete cascade,
  constraint evento_acceptance_responses_term_tenant_fkey
    foreign key (term_id, tenant_id)
    references public.tenant_acceptance_terms(id, tenant_id)
    on delete cascade,
  constraint evento_acceptance_responses_unique unique (evento_id, term_id)
);

create index evento_acceptance_responses_tenant_evento_idx
  on public.evento_acceptance_responses (tenant_id, evento_id);

create trigger set_evento_acceptance_responses_updated_at
before update on public.evento_acceptance_responses
for each row execute function public.set_updated_at();

alter table public.evento_acceptance_responses enable row level security;

create policy "evento_acceptance_responses_select_members"
on public.evento_acceptance_responses
for select to authenticated
using (public.is_tenant_member(tenant_id));

create policy "evento_acceptance_responses_insert_members"
on public.evento_acceptance_responses
for insert to authenticated
with check (public.is_tenant_member(tenant_id));

create policy "evento_acceptance_responses_update_members"
on public.evento_acceptance_responses
for update to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

create policy "evento_acceptance_responses_delete_members"
on public.evento_acceptance_responses
for delete to authenticated
using (public.is_tenant_member(tenant_id));

-- ---------------------------------------------------------------------------
-- 9. Seeds: payment methods e acceptance terms (tenants existentes)
-- ---------------------------------------------------------------------------

insert into public.tenant_payment_methods (
  tenant_id, name, payment_type, allows_installments, max_installments,
  allowed_for_deposit, allowed_for_remaining_balance, active, sort_order
)
select
  t.id,
  seed.name,
  seed.payment_type,
  seed.allows_installments,
  seed.max_installments,
  seed.allowed_for_deposit,
  seed.allowed_for_remaining_balance,
  true,
  seed.sort_order
from public.tenants t
cross join (
  values
    ('Pix', 'pix', false, null::integer, true, true, 1),
    ('Cartão de crédito', 'cartao_credito', true, 12, true, true, 2),
    ('Cartão de débito', 'cartao_debito', false, null, true, true, 3),
    ('Dinheiro', 'dinheiro', false, null, true, true, 4),
    ('Boleto', 'boleto', false, null, false, true, 5),
    ('Transferência', 'transferencia', false, null, true, true, 6)
) as seed(name, payment_type, allows_installments, max_installments, allowed_for_deposit, allowed_for_remaining_balance, sort_order)
on conflict (tenant_id, name) do nothing;

insert into public.tenant_acceptance_terms (
  tenant_id, term_key, title, content, is_required, appears_in_contract, is_system, active, sort_order
)
select
  t.id,
  seed.term_key,
  seed.title,
  seed.content,
  seed.is_required,
  seed.appears_in_contract,
  true,
  true,
  seed.sort_order
from public.tenants t
cross join (
  values
    (
      'termos_contratacao',
      'Aceito os termos de contratação',
      'Declaro que li e aceito os termos de contratação do espaço de festas.',
      true,
      true,
      1
    ),
    (
      'informacoes_verdadeiras',
      'Declaro que as informações preenchidas são verdadeiras',
      'Confirmo que todas as informações fornecidas neste formulário são verdadeiras e completas.',
      true,
      true,
      2
    ),
    (
      'politica_cancelamento',
      'Estou ciente da política de cancelamento',
      'Declaro estar ciente da política de cancelamento do espaço.',
      true,
      true,
      3
    ),
    (
      'politica_remarcacao',
      'Estou ciente da política de remarcação',
      'Declaro estar ciente da política de remarcação do espaço.',
      true,
      true,
      4
    ),
    (
      'regras_espaco',
      'Estou ciente das regras de uso do espaço',
      'Declaro estar ciente das regras de uso do espaço durante a realização da festa.',
      true,
      true,
      5
    ),
    (
      'uso_imagem',
      'Autorizo o uso de imagem para redes sociais',
      'Autorizo o uso de imagens e vídeos da festa para divulgação nas redes sociais do espaço.',
      false,
      true,
      6
    ),
    (
      'horarios_contratados',
      'Estou ciente dos horários contratados',
      'Confirmo estar ciente dos horários de início e término contratados para a festa.',
      true,
      true,
      7
    ),
    (
      'itens_inclusos',
      'Estou ciente dos itens inclusos e não inclusos',
      'Confirmo estar ciente dos itens inclusos e não inclusos no pacote e adicionais contratados.',
      true,
      true,
      8
    )
) as seed(term_key, title, content, is_required, appears_in_contract, sort_order)
on conflict (tenant_id, term_key) do nothing;

-- ---------------------------------------------------------------------------
-- 10. Atualizar trigger de seed para novos tenants
-- ---------------------------------------------------------------------------

create or replace function public.seed_tenant_closing_form_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.tenant_closing_form_fields (
    tenant_id, section, label, field_key, field_type, required, active, sort_order, is_system,
    category, is_locked, usage_contract, usage_party_summary, usage_ai, usage_reports
  )
  values
    (new.id, 'cliente', 'Nome completo', 'cliente_nome', 'text', true, true, 1, true, 'contratual', true, true, true, true, true),
    (new.id, 'cliente', 'Telefone', 'cliente_telefone', 'phone', true, true, 2, true, 'contratual', true, true, true, true, false),
    (new.id, 'cliente', 'E-mail', 'cliente_email', 'email', false, true, 3, true, 'contratual', false, true, false, true, false),
    (new.id, 'cliente', 'CPF', 'cliente_cpf', 'text', true, true, 4, true, 'contratual', true, true, true, true, true),
    (new.id, 'cliente', 'RG', 'cliente_rg', 'text', false, true, 5, true, 'contratual', false, true, false, false, false),
    (new.id, 'cliente', 'CEP', 'cliente_cep', 'text', true, true, 6, true, 'contratual', false, true, true, false, false),
    (new.id, 'cliente', 'Rua', 'cliente_rua', 'text', true, true, 7, true, 'contratual', false, true, true, false, false),
    (new.id, 'cliente', 'Número', 'cliente_numero', 'text', true, true, 8, true, 'contratual', false, true, true, false, false),
    (new.id, 'cliente', 'Bairro', 'cliente_bairro', 'text', true, true, 9, true, 'contratual', false, true, true, false, false),
    (new.id, 'cliente', 'Cidade', 'cliente_cidade', 'text', true, true, 10, true, 'contratual', false, true, true, false, false),
    (new.id, 'cliente', 'Estado', 'cliente_estado', 'text', true, true, 11, true, 'contratual', false, true, true, false, false),
    (new.id, 'aniversariante', 'Nome do aniversariante', 'aniversariante_nome', 'text', true, true, 1, true, 'operacional', true, false, true, true, true),
    (new.id, 'aniversariante', 'Data de nascimento', 'aniversariante_data_nascimento', 'date', true, true, 2, true, 'operacional', true, false, true, true, false),
    (new.id, 'aniversariante', 'Idade que irá completar', 'aniversariante_idade', 'number', true, true, 3, true, 'operacional', false, false, true, true, true),
    (new.id, 'aniversariante', 'Tema da festa', 'aniversariante_tema', 'text', true, true, 4, true, 'experiencia', false, false, true, true, false),
    (new.id, 'aniversariante', 'Personagem favorito', 'aniversariante_personagem', 'text', false, true, 5, true, 'experiencia', false, false, true, true, false),
    (new.id, 'festa', 'Data da festa', 'data_evento', 'date', true, true, 1, true, 'operacional', true, true, true, true, true),
    (new.id, 'festa', 'Horário de início', 'hora_evento', 'time', true, true, 2, true, 'operacional', true, true, true, true, false),
    (new.id, 'festa', 'Horário de término', 'hora_termino', 'time', true, true, 3, true, 'operacional', true, true, true, true, false),
    (new.id, 'festa', 'Quantidade de convidados', 'quantidade_convidados', 'number', true, true, 4, true, 'operacional', true, false, true, true, true),
    (new.id, 'festa', 'Número de adultos', 'quantidade_adultos', 'number', false, true, 5, true, 'operacional', false, false, true, true, true),
    (new.id, 'festa', 'Número de crianças', 'quantidade_crianas', 'number', false, true, 6, true, 'operacional', false, false, true, true, true),
    (new.id, 'festa', 'Observações gerais', 'observacoes_festa', 'textarea', false, true, 7, true, 'operacional', false, false, true, true, false),
    (new.id, 'pacote', 'Pacote escolhido', 'pacote_nome', 'text', true, true, 1, true, 'comercial', true, true, true, true, true),
    (new.id, 'pacote', 'Convidados inclusos no pacote', 'pacote_convidados_inclusos', 'number', true, true, 2, true, 'comercial', false, true, true, true, true),
    (new.id, 'pacote', 'Valor do pacote', 'valor_pacote', 'currency', true, true, 3, true, 'financeiro', true, true, false, false, true),
    (new.id, 'pacote', 'Itens inclusos', 'pacote_itens_inclusos', 'textarea', false, true, 4, true, 'comercial', false, true, true, true, false),
    (new.id, 'pacote', 'Itens não inclusos', 'pacote_itens_nao_inclusos', 'textarea', false, true, 5, true, 'comercial', false, true, true, true, false),
    (new.id, 'adicionais', 'Adicionais contratados', 'adicionais_selecionados', 'multiselect', false, true, 1, true, 'comercial', false, true, true, true, true),
    (new.id, 'adicionais', 'Valor dos adicionais', 'valor_adicionais', 'currency', false, true, 2, true, 'financeiro', false, true, false, false, true),
    (new.id, 'pagamento', 'Valor total', 'valor_total', 'currency', true, true, 1, true, 'financeiro', true, true, false, false, true),
    (new.id, 'pagamento', 'Valor da entrada', 'valor_entrada', 'currency', true, true, 2, true, 'financeiro', true, true, false, false, true),
    (new.id, 'pagamento', 'Forma de pagamento da entrada', 'forma_pagamento_entrada', 'select', true, true, 3, true, 'financeiro', false, true, false, false, true),
    (new.id, 'pagamento', 'Saldo restante', 'valor_saldo', 'currency', true, true, 4, true, 'financeiro', false, true, false, false, true),
    (new.id, 'pagamento', 'Forma de pagamento do saldo', 'forma_pagamento_saldo', 'select', true, true, 5, true, 'financeiro', false, true, false, false, true),
    (new.id, 'pagamento', 'Parcelamento', 'parcelas', 'number', false, true, 6, true, 'financeiro', false, false, false, false, true),
    (new.id, 'pagamento', 'Data limite de pagamento', 'data_limite_pagamento', 'date', false, true, 7, true, 'financeiro', false, true, false, false, true),
    (new.id, 'contrato', 'Observações do contrato', 'observacoes', 'textarea', false, true, 1, true, 'contratual', false, true, false, false, false)
  on conflict (tenant_id, field_key) do nothing;

  return new;
end;
$$;

create or replace function public.seed_tenant_payment_methods()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.tenant_payment_methods (
    tenant_id, name, payment_type, allows_installments, max_installments,
    allowed_for_deposit, allowed_for_remaining_balance, active, sort_order
  )
  values
    (new.id, 'Pix', 'pix', false, null, true, true, true, 1),
    (new.id, 'Cartão de crédito', 'cartao_credito', true, 12, true, true, true, 2),
    (new.id, 'Cartão de débito', 'cartao_debito', false, null, true, true, true, 3),
    (new.id, 'Dinheiro', 'dinheiro', false, null, true, true, true, 4),
    (new.id, 'Boleto', 'boleto', false, null, false, true, true, 5),
    (new.id, 'Transferência', 'transferencia', false, null, true, true, true, 6)
  on conflict (tenant_id, name) do nothing;

  return new;
end;
$$;

create or replace function public.seed_tenant_acceptance_terms()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.tenant_acceptance_terms (
    tenant_id, term_key, title, content, is_required, appears_in_contract, is_system, active, sort_order
  )
  values
    (new.id, 'termos_contratacao', 'Aceito os termos de contratação', 'Declaro que li e aceito os termos de contratação do espaço de festas.', true, true, true, true, 1),
    (new.id, 'informacoes_verdadeiras', 'Declaro que as informações preenchidas são verdadeiras', 'Confirmo que todas as informações fornecidas neste formulário são verdadeiras e completas.', true, true, true, true, 2),
    (new.id, 'politica_cancelamento', 'Estou ciente da política de cancelamento', 'Declaro estar ciente da política de cancelamento do espaço.', true, true, true, true, 3),
    (new.id, 'politica_remarcacao', 'Estou ciente da política de remarcação', 'Declaro estar ciente da política de remarcação do espaço.', true, true, true, true, 4),
    (new.id, 'regras_espaco', 'Estou ciente das regras de uso do espaço', 'Declaro estar ciente das regras de uso do espaço durante a realização da festa.', true, true, true, true, 5),
    (new.id, 'uso_imagem', 'Autorizo o uso de imagem para redes sociais', 'Autorizo o uso de imagens e vídeos da festa para divulgação nas redes sociais do espaço.', false, true, true, true, 6),
    (new.id, 'horarios_contratados', 'Estou ciente dos horários contratados', 'Confirmo estar ciente dos horários de início e término contratados para a festa.', true, true, true, true, 7),
    (new.id, 'itens_inclusos', 'Estou ciente dos itens inclusos e não inclusos', 'Confirmo estar ciente dos itens inclusos e não inclusos no pacote e adicionais contratados.', true, true, true, true, 8)
  on conflict (tenant_id, term_key) do nothing;

  return new;
end;
$$;

drop trigger if exists seed_payment_methods_on_tenant_create on public.tenants;
create trigger seed_payment_methods_on_tenant_create
after insert on public.tenants
for each row
execute function public.seed_tenant_payment_methods();

drop trigger if exists seed_acceptance_terms_on_tenant_create on public.tenants;
create trigger seed_acceptance_terms_on_tenant_create
after insert on public.tenants
for each row
execute function public.seed_tenant_acceptance_terms();
