create table public.subscription_plans (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text not null default '',
  monthly_price numeric(12, 2) not null,
  setup_price numeric(12, 2) not null default 0,
  setup_installments integer,
  loyalty_months integer,
  provider text not null default 'asaas',
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint subscription_plans_provider_check check (provider in ('asaas', 'stripe')),
  constraint subscription_plans_values_check check (
    monthly_price >= 0
    and setup_price >= 0
    and (setup_installments is null or setup_installments > 0)
    and (loyalty_months is null or loyalty_months >= 0)
  )
);

create table public.billing_customers (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete set null,
  provider text not null default 'asaas',
  provider_customer_id text,
  name text not null,
  email text not null,
  phone text,
  company_name text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint billing_customers_provider_check check (provider in ('asaas', 'stripe')),
  constraint billing_customers_provider_customer_unique unique (provider, provider_customer_id)
);

create table public.billing_subscriptions (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete set null,
  plan_id bigint references public.subscription_plans(id) on delete restrict,
  customer_id bigint references public.billing_customers(id) on delete restrict,
  provider text not null default 'asaas',
  provider_subscription_id text,
  external_reference text not null unique,
  status text not null default 'pending',
  checkout_url text,
  next_due_date date,
  current_period_end date,
  canceled_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint billing_subscriptions_provider_check check (provider in ('asaas', 'stripe')),
  constraint billing_subscriptions_status_check check (
    status in ('pending', 'trialing', 'active', 'past_due', 'canceled', 'failed')
  ),
  constraint billing_subscriptions_provider_subscription_unique unique (provider, provider_subscription_id)
);

create table public.billing_webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  external_event_id text not null,
  event_type text not null,
  processed_at timestamptz,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  constraint billing_webhook_events_provider_check check (provider in ('asaas', 'stripe')),
  constraint billing_webhook_events_unique unique (provider, external_event_id)
);

create index subscription_plans_active_idx on public.subscription_plans (active, provider);
create index billing_customers_tenant_idx on public.billing_customers (tenant_id);
create index billing_subscriptions_tenant_idx on public.billing_subscriptions (tenant_id, status);
create index billing_subscriptions_provider_idx on public.billing_subscriptions (provider, provider_subscription_id);
create index billing_webhook_events_type_idx on public.billing_webhook_events (provider, event_type, created_at desc);

create trigger set_subscription_plans_updated_at before update on public.subscription_plans
for each row execute function public.set_updated_at();
create trigger set_billing_customers_updated_at before update on public.billing_customers
for each row execute function public.set_updated_at();
create trigger set_billing_subscriptions_updated_at before update on public.billing_subscriptions
for each row execute function public.set_updated_at();

alter table public.subscription_plans enable row level security;
alter table public.billing_customers enable row level security;
alter table public.billing_subscriptions enable row level security;
alter table public.billing_webhook_events enable row level security;

create policy "subscription_plans_select_active"
on public.subscription_plans
for select
to anon, authenticated
using (active = true);

create policy "billing_customers_select_members"
on public.billing_customers
for select
to authenticated
using (tenant_id is not null and public.is_tenant_member(tenant_id));

create policy "billing_subscriptions_select_members"
on public.billing_subscriptions
for select
to authenticated
using (tenant_id is not null and public.is_tenant_member(tenant_id));

insert into public.subscription_plans
  (slug, name, description, monthly_price, setup_price, setup_installments, loyalty_months, provider, metadata)
values
  ('starter', 'Starter', 'CRM, calendario e checklist para iniciar a operacao.', 199, 1500, null, null, 'asaas', '{"highlight": false}'::jsonb),
  ('profissional', 'Profissional', 'Relatorios, configuracoes comerciais e suporte prioritario.', 349, 3000, 3, 12, 'asaas', '{"highlight": true}'::jsonb),
  ('enterprise', 'Enterprise', 'Plano para operacoes maiores e integracoes personalizadas.', 599, 6000, 6, 12, 'asaas', '{"highlight": false}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  monthly_price = excluded.monthly_price,
  setup_price = excluded.setup_price,
  setup_installments = excluded.setup_installments,
  loyalty_months = excluded.loyalty_months,
  provider = excluded.provider,
  metadata = excluded.metadata,
  active = true;
