-- Histórico de mensagens do WhatsApp da plataforma (inbox admin).

create table if not exists public.platform_whatsapp_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.platform_whatsapp_conversations (id) on delete cascade,
  connection_id bigint not null references public.whatsapp_connections (id) on delete cascade,
  evolution_message_id text,
  direction text not null,
  body text,
  message_type text not null default 'text',
  from_me boolean not null default false,
  sent_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint platform_whatsapp_messages_direction_check check (
    direction in ('inbound', 'outbound')
  )
);

create unique index if not exists platform_whatsapp_messages_evolution_id_unique
  on public.platform_whatsapp_messages (connection_id, evolution_message_id)
  where evolution_message_id is not null;

create index if not exists platform_whatsapp_messages_conversation_sent_at_idx
  on public.platform_whatsapp_messages (conversation_id, sent_at asc);

alter table public.platform_whatsapp_messages enable row level security;

drop policy if exists "platform_whatsapp_messages_select_platform_admin"
  on public.platform_whatsapp_messages;
create policy "platform_whatsapp_messages_select_platform_admin"
on public.platform_whatsapp_messages
for select to authenticated
using (public.is_platform_admin());

drop policy if exists "platform_whatsapp_messages_insert_platform_admin"
  on public.platform_whatsapp_messages;
create policy "platform_whatsapp_messages_insert_platform_admin"
on public.platform_whatsapp_messages
for insert to authenticated
with check (public.is_platform_admin());

drop policy if exists "platform_whatsapp_messages_update_platform_admin"
  on public.platform_whatsapp_messages;
create policy "platform_whatsapp_messages_update_platform_admin"
on public.platform_whatsapp_messages
for update to authenticated
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists "platform_whatsapp_messages_delete_platform_admin"
  on public.platform_whatsapp_messages;
create policy "platform_whatsapp_messages_delete_platform_admin"
on public.platform_whatsapp_messages
for delete to authenticated
using (public.is_platform_admin());

grant select, insert, update, delete on public.platform_whatsapp_messages to authenticated;
grant all on public.platform_whatsapp_messages to service_role;
grant usage, select on sequence public.platform_whatsapp_messages_id_seq to authenticated, service_role;
