-- WhatsApp da plataforma FestaAI (admin): scope em conexões + funil de conversas.

-- 1) Escopo platform | tenant em whatsapp_connections
alter table public.whatsapp_connections
  alter column tenant_id drop not null;

alter table public.whatsapp_connections
  add column if not exists scope text not null default 'tenant';

alter table public.whatsapp_connections
  drop constraint if exists whatsapp_connections_scope_check;

alter table public.whatsapp_connections
  add constraint whatsapp_connections_scope_check
  check (scope in ('tenant', 'platform'));

alter table public.whatsapp_connections
  drop constraint if exists whatsapp_connections_scope_tenant_check;

alter table public.whatsapp_connections
  add constraint whatsapp_connections_scope_tenant_check
  check (
    (scope = 'tenant' and tenant_id is not null)
    or (scope = 'platform' and tenant_id is null)
  );

create index if not exists whatsapp_connections_scope_idx
  on public.whatsapp_connections (scope);

-- MVP: no máximo uma conexão da plataforma
create unique index if not exists whatsapp_connections_platform_unique
  on public.whatsapp_connections ((scope))
  where scope = 'platform';

-- RLS: platform admin gerencia conexões da plataforma
-- SELECT: platform admin lê todas (tenant + platform) — ver migration fix se necessário
drop policy if exists "whatsapp_connections_select_platform_admin" on public.whatsapp_connections;
create policy "whatsapp_connections_select_platform_admin"
on public.whatsapp_connections
for select to authenticated
using (public.is_platform_admin());

drop policy if exists "whatsapp_connections_insert_platform_admin" on public.whatsapp_connections;
create policy "whatsapp_connections_insert_platform_admin"
on public.whatsapp_connections
for insert to authenticated
with check (scope = 'platform' and public.is_platform_admin());

drop policy if exists "whatsapp_connections_update_platform_admin" on public.whatsapp_connections;
create policy "whatsapp_connections_update_platform_admin"
on public.whatsapp_connections
for update to authenticated
using (scope = 'platform' and public.is_platform_admin())
with check (scope = 'platform' and public.is_platform_admin());

drop policy if exists "whatsapp_connections_delete_platform_admin" on public.whatsapp_connections;
create policy "whatsapp_connections_delete_platform_admin"
on public.whatsapp_connections
for delete to authenticated
using (scope = 'platform' and public.is_platform_admin());

-- Ajustar políticas de tenant para não enxergar scope platform
drop policy if exists "whatsapp_connections_select_tenant_member" on public.whatsapp_connections;
create policy "whatsapp_connections_select_tenant_member"
on public.whatsapp_connections
for select to authenticated
using (
  scope = 'tenant'
  and tenant_id is not null
  and public.is_tenant_member(tenant_id)
);

drop policy if exists "whatsapp_connections_insert_tenant_admin" on public.whatsapp_connections;
create policy "whatsapp_connections_insert_tenant_admin"
on public.whatsapp_connections
for insert to authenticated
with check (
  scope = 'tenant'
  and tenant_id is not null
  and public.has_tenant_role(tenant_id, array['owner', 'admin'])
);

drop policy if exists "whatsapp_connections_update_tenant_admin" on public.whatsapp_connections;
create policy "whatsapp_connections_update_tenant_admin"
on public.whatsapp_connections
for update to authenticated
using (
  scope = 'tenant'
  and tenant_id is not null
  and public.has_tenant_role(tenant_id, array['owner', 'admin'])
)
with check (
  scope = 'tenant'
  and tenant_id is not null
  and public.has_tenant_role(tenant_id, array['owner', 'admin'])
);

drop policy if exists "whatsapp_connections_delete_tenant_admin" on public.whatsapp_connections;
create policy "whatsapp_connections_delete_tenant_admin"
on public.whatsapp_connections
for delete to authenticated
using (
  scope = 'tenant'
  and tenant_id is not null
  and public.has_tenant_role(tenant_id, array['owner', 'admin'])
);

-- 2) Funil de conversas do número da plataforma
create table if not exists public.platform_whatsapp_conversations (
  id bigint generated by default as identity primary key,
  connection_id bigint not null references public.whatsapp_connections (id) on delete cascade,
  customer_phone text not null,
  customer_name text,
  stage text not null default 'contato_inicial',
  lost_reason text,
  last_message_at timestamptz,
  last_message_preview text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint platform_whatsapp_conversations_connection_phone_unique
    unique (connection_id, customer_phone),
  constraint platform_whatsapp_conversations_stage_check check (
    stage in (
      'contato_inicial',
      'em_conversa',
      'demonstracao_agendada',
      'proposta_enviada',
      'perdido'
    )
  )
);

create index if not exists platform_whatsapp_conversations_stage_idx
  on public.platform_whatsapp_conversations (stage);

create index if not exists platform_whatsapp_conversations_last_message_at_idx
  on public.platform_whatsapp_conversations (last_message_at desc nulls last);

create trigger set_platform_whatsapp_conversations_updated_at
before update on public.platform_whatsapp_conversations
for each row execute function public.set_updated_at();

alter table public.platform_whatsapp_conversations enable row level security;

drop policy if exists "platform_whatsapp_conversations_select_platform_admin"
  on public.platform_whatsapp_conversations;
create policy "platform_whatsapp_conversations_select_platform_admin"
on public.platform_whatsapp_conversations
for select to authenticated
using (public.is_platform_admin());

drop policy if exists "platform_whatsapp_conversations_insert_platform_admin"
  on public.platform_whatsapp_conversations;
create policy "platform_whatsapp_conversations_insert_platform_admin"
on public.platform_whatsapp_conversations
for insert to authenticated
with check (public.is_platform_admin());

drop policy if exists "platform_whatsapp_conversations_update_platform_admin"
  on public.platform_whatsapp_conversations;
create policy "platform_whatsapp_conversations_update_platform_admin"
on public.platform_whatsapp_conversations
for update to authenticated
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists "platform_whatsapp_conversations_delete_platform_admin"
  on public.platform_whatsapp_conversations;
create policy "platform_whatsapp_conversations_delete_platform_admin"
on public.platform_whatsapp_conversations
for delete to authenticated
using (public.is_platform_admin());

grant select, insert, update, delete on public.platform_whatsapp_conversations to authenticated;
grant all on public.platform_whatsapp_conversations to service_role;
grant usage, select on sequence public.platform_whatsapp_conversations_id_seq to authenticated, service_role;
