-- Fundação multi-tenant para conexões WhatsApp via Evolution API.
-- Transição segura: remove WIP tenant_evolution_connections se existir (apenas local/dev).

drop table if exists public.tenant_evolution_connections cascade;

create table public.whatsapp_connections (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants (id) on delete cascade,
  name text not null,
  type text not null default 'whatsapp',
  provider text not null default 'evolution',
  instance_name text not null,
  phone text,
  status text not null default 'connecting',
  qr_code text,
  webhook_url text,
  last_seen_at timestamptz,
  last_error text,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint whatsapp_connections_instance_name_unique unique (instance_name),
  constraint whatsapp_connections_status_check check (
    status in ('connecting', 'connected', 'disconnected', 'error')
  )
);

create index whatsapp_connections_tenant_id_idx on public.whatsapp_connections (tenant_id);
create index whatsapp_connections_instance_name_idx on public.whatsapp_connections (instance_name);
create index whatsapp_connections_tenant_status_idx on public.whatsapp_connections (tenant_id, status);

create trigger set_whatsapp_connections_updated_at
before update on public.whatsapp_connections
for each row execute function public.set_updated_at();

alter table public.whatsapp_connections enable row level security;

create policy "whatsapp_connections_select_tenant_member"
on public.whatsapp_connections
for select to authenticated
using (public.is_tenant_member (tenant_id));

create policy "whatsapp_connections_insert_tenant_admin"
on public.whatsapp_connections
for insert to authenticated
with check (public.has_tenant_role (tenant_id, array['owner', 'admin']));

create policy "whatsapp_connections_update_tenant_admin"
on public.whatsapp_connections
for update to authenticated
using (public.has_tenant_role (tenant_id, array['owner', 'admin']))
with check (public.has_tenant_role (tenant_id, array['owner', 'admin']));

create policy "whatsapp_connections_delete_tenant_admin"
on public.whatsapp_connections
for delete to authenticated
using (public.has_tenant_role (tenant_id, array['owner', 'admin']));

-- Segredos de webhook: somente service_role (Edge Functions).
create table public.whatsapp_connection_webhook_secrets (
  connection_id bigint primary key references public.whatsapp_connections (id) on delete cascade,
  instance_name text not null,
  webhook_token text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint whatsapp_connection_webhook_secrets_instance_name_unique unique (instance_name)
);

create trigger set_whatsapp_connection_webhook_secrets_updated_at
before update on public.whatsapp_connection_webhook_secrets
for each row execute function public.set_updated_at();

alter table public.whatsapp_connection_webhook_secrets enable row level security;

create policy "whatsapp_connection_webhook_secrets_no_client_access"
on public.whatsapp_connection_webhook_secrets
for all to anon, authenticated
using (false)
with check (false);

revoke all on table public.whatsapp_connection_webhook_secrets from anon, authenticated;
grant all on table public.whatsapp_connection_webhook_secrets to service_role;

-- Logs de ingestão de webhook: somente service_role.
create table public.whatsapp_webhook_ingest_logs (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants (id) on delete set null,
  source text not null default 'evolution-connection-webhook',
  event text,
  instance_name text,
  auth_status text not null,
  processing_status text not null default 'received',
  payload jsonb,
  error_message text,
  created_at timestamptz not null default now(),
  constraint whatsapp_webhook_ingest_logs_auth_status_check check (
    auth_status in ('valid', 'invalid', 'missing', 'disabled')
  ),
  constraint whatsapp_webhook_ingest_logs_processing_status_check check (
    processing_status in ('received', 'processed', 'skipped', 'rejected')
  )
);

create index whatsapp_webhook_ingest_logs_tenant_id_idx on public.whatsapp_webhook_ingest_logs (tenant_id);
create index whatsapp_webhook_ingest_logs_instance_name_idx on public.whatsapp_webhook_ingest_logs (instance_name);
create index whatsapp_webhook_ingest_logs_created_at_idx on public.whatsapp_webhook_ingest_logs (created_at desc);

alter table public.whatsapp_webhook_ingest_logs enable row level security;

create policy "whatsapp_webhook_ingest_logs_no_client_access"
on public.whatsapp_webhook_ingest_logs
for all to anon, authenticated
using (false)
with check (false);

revoke all on table public.whatsapp_webhook_ingest_logs from anon, authenticated;
grant all on table public.whatsapp_webhook_ingest_logs to service_role;
