create table public.email_events (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete set null,
  provider text not null default 'brevo',
  template_key text not null,
  recipient_email text not null,
  recipient_name text,
  subject text not null,
  status text not null default 'queued',
  provider_message_id text,
  error_message text,
  payload jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  constraint email_events_provider_check check (provider in ('brevo')),
  constraint email_events_status_check check (status in ('queued', 'sent', 'failed', 'skipped')),
  constraint email_events_recipient_email_check check (recipient_email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')
);

create index email_events_tenant_idx on public.email_events (tenant_id, created_at desc);
create index email_events_status_idx on public.email_events (status, created_at desc);
create index email_events_template_idx on public.email_events (template_key, created_at desc);

alter table public.email_events enable row level security;

create policy "email_events_select_members"
on public.email_events
for select
to authenticated
using (tenant_id is not null and public.is_tenant_member(tenant_id));
