-- Aceites do contrato comercial FestaAI (contratação SaaS)

create table if not exists public.billing_contract_acceptances (
  id bigint generated by default as identity primary key,
  billing_subscription_id bigint not null references public.billing_subscriptions (id) on delete cascade,
  contract_version text not null,
  contract_body_snapshot text not null,
  commercial_annex_snapshot text not null,
  commercial_snapshot jsonb not null default '{}'::jsonb,
  acceptance_declaration text not null,
  accepted_by_name text not null,
  accepted_by_email text not null,
  accepted_by_cpf_cnpj text,
  accepted_by_company text,
  accepted_at timestamptz not null default now(),
  ip_address inet,
  user_agent text,
  external_reference text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint billing_contract_acceptances_name_check check (char_length(trim(accepted_by_name)) > 0),
  constraint billing_contract_acceptances_email_check check (char_length(trim(accepted_by_email)) > 0),
  constraint billing_contract_acceptances_subscription_unique unique (billing_subscription_id)
);

create index if not exists billing_contract_acceptances_accepted_at_idx
  on public.billing_contract_acceptances (accepted_at desc);

create index if not exists billing_contract_acceptances_email_idx
  on public.billing_contract_acceptances (accepted_by_email);

alter table public.billing_contract_acceptances enable row level security;

drop policy if exists "billing_contract_acceptances_select_platform_admin"
  on public.billing_contract_acceptances;
create policy "billing_contract_acceptances_select_platform_admin"
on public.billing_contract_acceptances
for select to authenticated
using (public.is_platform_admin());

-- Histórico de reajustes anuais de mensalidade

create table if not exists public.billing_subscription_adjustments (
  id bigint generated by default as identity primary key,
  billing_subscription_id bigint not null references public.billing_subscriptions (id) on delete cascade,
  previous_monthly_price numeric(12, 2) not null,
  new_monthly_price numeric(12, 2) not null,
  adjustment_rate numeric(8, 6) not null,
  adjustment_index text not null default 'IPCA',
  provider_subscription_id text,
  asaas_updated boolean not null default false,
  notified_at timestamptz,
  effective_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint billing_subscription_adjustments_prices_check check (new_monthly_price > 0)
);

create index if not exists billing_subscription_adjustments_subscription_idx
  on public.billing_subscription_adjustments (billing_subscription_id, effective_at desc);

alter table public.billing_subscription_adjustments enable row level security;

drop policy if exists "billing_subscription_adjustments_select_platform_admin"
  on public.billing_subscription_adjustments;
create policy "billing_subscription_adjustments_select_platform_admin"
on public.billing_subscription_adjustments
for select to authenticated
using (public.is_platform_admin());

comment on table public.billing_contract_acceptances is
  'Registro imutável do aceite eletrônico do contrato comercial FestaAI no checkout.';
comment on table public.billing_subscription_adjustments is
  'Histórico de reajustes anuais aplicados às mensalidades via Asaas.';
