-- Fase H: Contrato e aceite formal por evento

-- ---------------------------------------------------------------------------
-- 1. tenant_contract_templates
-- ---------------------------------------------------------------------------

create table if not exists public.tenant_contract_templates (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  name text not null,
  description text,
  template_html text not null,
  version integer not null default 1,
  is_active boolean not null default true,
  is_default boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_contract_templates_name_check check (char_length(trim(name)) > 0),
  constraint tenant_contract_templates_html_check check (char_length(trim(template_html)) > 0)
);

create unique index if not exists tenant_contract_templates_default_idx
  on public.tenant_contract_templates (tenant_id)
  where is_default = true;

create index if not exists tenant_contract_templates_tenant_idx
  on public.tenant_contract_templates (tenant_id, is_active);

drop trigger if exists set_tenant_contract_templates_updated_at on public.tenant_contract_templates;
create trigger set_tenant_contract_templates_updated_at
before update on public.tenant_contract_templates
for each row execute function public.set_updated_at();

alter table public.tenant_contract_templates enable row level security;

drop policy if exists "tenant_contract_templates_members_all" on public.tenant_contract_templates;
create policy "tenant_contract_templates_members_all"
on public.tenant_contract_templates
for all to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

alter table public.tenant_contract_templates
  drop constraint if exists tenant_contract_templates_id_tenant_id_key;
alter table public.tenant_contract_templates
  add constraint tenant_contract_templates_id_tenant_id_key unique (id, tenant_id);

-- ---------------------------------------------------------------------------
-- 2. evento_contracts
-- ---------------------------------------------------------------------------

do $$
begin
  if not exists (select 1 from pg_type where typname = 'evento_contract_status') then
    create type public.evento_contract_status as enum (
      'draft',
      'generated',
      'accepted',
      'cancelled',
      'superseded'
    );
  end if;
end $$;

create table if not exists public.evento_contracts (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  evento_id bigint not null,
  template_id bigint not null,
  status public.evento_contract_status not null default 'generated',
  contract_number text not null,
  contract_html text not null,
  contract_text text,
  contract_snapshot jsonb not null default '{}'::jsonb,
  contract_hash text not null,
  template_version integer not null default 1,
  generated_at timestamptz not null default now(),
  accepted_at timestamptz,
  superseded_by bigint,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint evento_contracts_evento_tenant_fkey
    foreign key (evento_id, tenant_id)
    references public.eventos(id, tenant_id)
    on delete cascade,
  constraint evento_contracts_template_tenant_fkey
    foreign key (template_id, tenant_id)
    references public.tenant_contract_templates(id, tenant_id),
  constraint evento_contracts_number_unique unique (tenant_id, contract_number)
);

create unique index if not exists evento_contracts_active_unique
  on public.evento_contracts (tenant_id, evento_id)
  where status in ('generated', 'accepted');

create index if not exists evento_contracts_tenant_evento_idx
  on public.evento_contracts (tenant_id, evento_id, status);

alter table public.evento_contracts
  drop constraint if exists evento_contracts_superseded_by_fkey;
alter table public.evento_contracts
  add constraint evento_contracts_superseded_by_fkey
  foreign key (superseded_by) references public.evento_contracts(id) on delete set null;

alter table public.evento_contracts
  drop constraint if exists evento_contracts_id_tenant_id_key;
alter table public.evento_contracts
  add constraint evento_contracts_id_tenant_id_key unique (id, tenant_id);

drop trigger if exists set_evento_contracts_updated_at on public.evento_contracts;
create trigger set_evento_contracts_updated_at
before update on public.evento_contracts
for each row execute function public.set_updated_at();

create or replace function public.prevent_accepted_contract_content_mutation()
returns trigger
language plpgsql
as $$
begin
  if old.status = 'accepted' then
    if new.contract_html is distinct from old.contract_html
       or new.contract_snapshot is distinct from old.contract_snapshot
       or new.contract_hash is distinct from old.contract_hash
       or new.contract_number is distinct from old.contract_number then
      raise exception 'Contrato aceito nao pode ter conteudo alterado';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists prevent_accepted_contract_content_mutation on public.evento_contracts;
create trigger prevent_accepted_contract_content_mutation
before update on public.evento_contracts
for each row execute function public.prevent_accepted_contract_content_mutation();

alter table public.evento_contracts enable row level security;

drop policy if exists "evento_contracts_members_all" on public.evento_contracts;
create policy "evento_contracts_members_all"
on public.evento_contracts
for all to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

-- ---------------------------------------------------------------------------
-- 3. evento_contract_acceptances
-- ---------------------------------------------------------------------------

create table if not exists public.evento_contract_acceptances (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  evento_id bigint not null,
  contract_id bigint not null,
  accepted_by_name text not null,
  accepted_by_cpf text,
  accepted_by_email text,
  accepted_by_phone text,
  accepted_at timestamptz not null default now(),
  ip_address inet,
  user_agent text,
  acceptance_text text not null,
  accepted_terms_snapshot jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint evento_contract_acceptances_evento_tenant_fkey
    foreign key (evento_id, tenant_id)
    references public.eventos(id, tenant_id)
    on delete cascade,
  constraint evento_contract_acceptances_contract_tenant_fkey
    foreign key (contract_id, tenant_id)
    references public.evento_contracts(id, tenant_id),
  constraint evento_contract_acceptances_contract_unique unique (contract_id),
  constraint evento_contract_acceptances_name_check check (char_length(trim(accepted_by_name)) > 0)
);

create index if not exists evento_contract_acceptances_tenant_evento_idx
  on public.evento_contract_acceptances (tenant_id, evento_id);

alter table public.evento_contract_acceptances enable row level security;

drop policy if exists "evento_contract_acceptances_members_all" on public.evento_contract_acceptances;
create policy "evento_contract_acceptances_members_all"
on public.evento_contract_acceptances
for all to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

-- ---------------------------------------------------------------------------
-- 4. Seed template padrao (tenants existentes)
-- ---------------------------------------------------------------------------

insert into public.tenant_contract_templates (
  tenant_id, name, description, template_html, version, is_active, is_default
)
select
  t.id,
  'Contrato padrão de festa infantil',
  'Modelo operacional base para contratação de festas.',
  $template$<article class="contract-document">
<h1>CONTRATO DE PRESTAÇÃO DE SERVIÇOS PARA FESTA INFANTIL</h1>
<p><strong>Nº:</strong> {{contract_number}}</p>

<h2>1. Partes</h2>
<p><strong>CONTRATADA:</strong> Espaço de festas (conforme cadastro do estabelecimento).</p>
<p><strong>CONTRATANTE:</strong> {{cliente_nome}}, CPF {{cliente_cpf}}, RG {{cliente_rg}}, residente em {{cliente_endereco}}.</p>
<p><strong>Contato:</strong> {{cliente_telefone}} · {{cliente_email}}</p>

<h2>2. Dados da festa</h2>
<ul>
  <li><strong>Aniversariante:</strong> {{aniversariante_nome}}</li>
  <li><strong>Data de nascimento:</strong> {{aniversariante_data_nascimento}}</li>
  <li><strong>Data da festa:</strong> {{data_evento}}</li>
  <li><strong>Horário:</strong> {{hora_evento}} às {{hora_termino}}</li>
  <li><strong>Convidados:</strong> {{quantidade_convidados}} (adultos: {{quantidade_adultos}}, crianças: {{quantidade_crianas}})</li>
  <li><strong>Tema:</strong> {{aniversariante_tema}}</li>
</ul>

<h2>3. Pacote contratado</h2>
<p><strong>Pacote:</strong> {{pacote_nome}}</p>
<p><strong>Convidados inclusos no pacote:</strong> {{pacote_convidados_inclusos}}</p>
<p><strong>Itens inclusos:</strong></p>
<pre>{{itens_inclusos}}</pre>
<p><strong>Itens não inclusos:</strong></p>
<pre>{{itens_nao_inclusos}}</pre>

<h2>4. Adicionais contratados</h2>
<pre>{{adicionais_contratados}}</pre>

<h2>5. Valores e pagamento</h2>
<ul>
  <li><strong>Valor do pacote:</strong> {{valor_pacote}}</li>
  <li><strong>Valor dos adicionais:</strong> {{valor_adicionais}}</li>
  <li><strong>Valor total:</strong> {{valor_total}}</li>
  <li><strong>Entrada:</strong> {{valor_entrada}}</li>
  <li><strong>Saldo:</strong> {{valor_saldo}}</li>
  <li><strong>Forma de pagamento da entrada:</strong> {{forma_pagamento_entrada}}</li>
  <li><strong>Forma de pagamento do saldo:</strong> {{forma_pagamento_saldo}}</li>
  <li><strong>Parcelamento:</strong> {{parcelas}} parcela(s)</li>
</ul>

<h2>6. Política de cancelamento</h2>
<p>{{politica_cancelamento}}</p>

<h2>7. Política de remarcação</h2>
<p>{{politica_remarcacao}}</p>

<h2>8. Observações</h2>
<p>{{observacoes}}</p>
<p>{{observacoes_festa}}</p>

<h2>9. Termos e autorizações</h2>
<pre>{{aceites}}</pre>

<h2>10. Aceite eletrônico</h2>
<p>O CONTRATANTE declara ter lido, compreendido e aceito integralmente as condições deste contrato, inclusive valores, forma de pagamento, data, horário, pacote contratado, políticas de cancelamento e remarcação e regras de uso do espaço.</p>
</article>$template$,
  1,
  true,
  true
from public.tenants t
where not exists (
  select 1
  from public.tenant_contract_templates ct
  where ct.tenant_id = t.id and ct.is_default = true
);

-- ---------------------------------------------------------------------------
-- 5. Seed template para novos tenants
-- ---------------------------------------------------------------------------

create or replace function public.seed_tenant_contract_template()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.tenant_contract_templates (
    tenant_id, name, description, template_html, version, is_active, is_default
  )
  values (
    new.id,
    'Contrato padrão de festa infantil',
    'Modelo operacional base para contratação de festas.',
    $template$<article class="contract-document">
<h1>CONTRATO DE PRESTAÇÃO DE SERVIÇOS PARA FESTA INFANTIL</h1>
<p><strong>Nº:</strong> {{contract_number}}</p>
<h2>1. Partes</h2>
<p><strong>CONTRATANTE:</strong> {{cliente_nome}}, CPF {{cliente_cpf}}</p>
<h2>2. Dados da festa</h2>
<p>Aniversariante: {{aniversariante_nome}} · Data: {{data_evento}} · Horário: {{hora_evento}} às {{hora_termino}}</p>
<h2>3. Pacote</h2>
<p>{{pacote_nome}} — {{valor_pacote}}</p>
<h2>4. Adicionais</h2>
<pre>{{adicionais_contratados}}</pre>
<h2>5. Valores</h2>
<p>Total: {{valor_total}} · Entrada: {{valor_entrada}} · Saldo: {{valor_saldo}}</p>
<h2>6. Políticas</h2>
<p>{{politica_cancelamento}}</p>
<p>{{politica_remarcacao}}</p>
<h2>7. Aceites</h2>
<pre>{{aceites}}</pre>
</article>$template$,
    1,
    true,
    true
  )
  on conflict do nothing;

  return new;
end;
$$;

drop trigger if exists seed_contract_template_on_tenant_create on public.tenants;
create trigger seed_contract_template_on_tenant_create
after insert on public.tenants
for each row execute function public.seed_tenant_contract_template();
