-- Relatórios de erro com anexos (prints) no Storage; sem envio por e-mail.

create table public.support_error_reports (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants (id) on delete cascade,
  created_by uuid references public.profiles (id) on delete set null,
  title text not null,
  description text not null,
  created_at timestamptz not null default now(),
  constraint support_error_reports_title_len check (char_length(trim(title)) >= 3),
  constraint support_error_reports_description_len check (char_length(trim(description)) >= 10)
);

comment on table public.support_error_reports is 'Reportes de bugs/incidentes pelo cliente (tenant admin); arquivos em bucket support-error-reports.';

create index support_error_reports_tenant_id_created_at_idx on public.support_error_reports (tenant_id, created_at desc);

create table public.support_error_report_files (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.support_error_reports (id) on delete cascade,
  storage_path text not null,
  file_name text not null,
  content_type text,
  byte_size bigint not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  constraint support_error_report_files_path_unique unique (storage_path),
  constraint support_error_report_files_byte_size_positive check (byte_size > 0)
);

comment on table public.support_error_report_files is 'Metadados de anexos de relatório de erro (path no Storage).';

create index support_error_report_files_report_id_idx on public.support_error_report_files (report_id);

alter table public.support_error_reports enable row level security;

alter table public.support_error_report_files enable row level security;

create policy "support_error_reports_select_tenant_admins"
on public.support_error_reports
for select
to authenticated
using (public.has_tenant_role (tenant_id, array['owner', 'admin']));

create policy "support_error_reports_insert_tenant_admins"
on public.support_error_reports
for insert
to authenticated
with check (
  public.has_tenant_role (tenant_id, array['owner', 'admin'])
  and created_by = auth.uid ()
);

create policy "support_error_reports_delete_tenant_admins"
on public.support_error_reports
for delete
to authenticated
using (public.has_tenant_role (tenant_id, array['owner', 'admin']));

create policy "support_error_reports_select_platform_admin"
on public.support_error_reports
for select
to authenticated
using (public.is_platform_admin ());

create policy "support_error_report_files_select_tenant_admins"
on public.support_error_report_files
for select
to authenticated
using (
  exists (
    select 1
    from public.support_error_reports r
    where r.id = report_id
      and public.has_tenant_role (r.tenant_id, array['owner', 'admin'])
  )
);

create policy "support_error_report_files_insert_tenant_admins"
on public.support_error_report_files
for insert
to authenticated
with check (
  exists (
    select 1
    from public.support_error_reports r
    where r.id = report_id
      and public.has_tenant_role (r.tenant_id, array['owner', 'admin'])
  )
);

create policy "support_error_report_files_select_platform_admin"
on public.support_error_report_files
for select
to authenticated
using (public.is_platform_admin ());

insert into storage.buckets (id, name, public, file_size_limit)
values ('support-error-reports', 'support-error-reports', false, 5242880)
on conflict (id) do update
set file_size_limit = excluded.file_size_limit;

-- Path: {tenant_id}/{report_id}/{uuid}_{filename}
create policy "support_error_reports_storage_insert"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'support-error-reports'
  and coalesce (array_length (storage.foldername (name), 1), 0) >= 3
  and public.has_tenant_role ((storage.foldername (name))[1]::bigint, array['owner', 'admin'])
  and exists (
    select 1
    from public.support_error_reports r
    where r.id = (storage.foldername (name))[2]::bigint
      and r.tenant_id = (storage.foldername (name))[1]::bigint
  )
);

create policy "support_error_reports_storage_select"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'support-error-reports'
  and (
    public.is_platform_admin ()
    or (
      coalesce (array_length (storage.foldername (name), 1), 0) >= 1
      and public.has_tenant_role ((storage.foldername (name))[1]::bigint, array['owner', 'admin'])
    )
  )
);

create policy "support_error_reports_storage_delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'support-error-reports'
  and (
    public.is_platform_admin ()
    or (
      coalesce (array_length (storage.foldername (name), 1), 0) >= 1
      and public.has_tenant_role ((storage.foldername (name))[1]::bigint, array['owner', 'admin'])
    )
  )
);
