-- Radar Comercial: tabelas de CRM, RLS no schema radar e RPCs para platform admin.
-- Não altera nem apaga dados das tabelas de coleta existentes.

-- ---------------------------------------------------------------------------
-- 1) Tabelas de acompanhamento comercial
-- ---------------------------------------------------------------------------

create table if not exists radar.company_crm (
  id bigint generated by default as identity primary key,
  company_id bigint not null references radar.market_companies (id) on delete cascade,
  status text not null default 'new'
    check (
      status = any (
        array[
          'new',
          'prospecting',
          'contacted',
          'responded',
          'meeting_scheduled',
          'proposal_sent',
          'won',
          'lost',
          'do_not_contact'
        ]
      )
    ),
  assigned_user_id uuid references public.profiles (id) on delete set null,
  priority text not null default 'medium'
    check (priority = any (array['high', 'medium', 'low'])),
  last_contact_at timestamptz,
  next_action_at timestamptz,
  next_action_description text,
  lost_reason text,
  do_not_contact boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint company_crm_company_id_key unique (company_id)
);

create table if not exists radar.company_crm_interactions (
  id bigint generated by default as identity primary key,
  company_id bigint not null references radar.market_companies (id) on delete cascade,
  interaction_type text not null
    check (
      interaction_type = any (
        array[
          'whatsapp',
          'phone',
          'instagram',
          'email',
          'meeting',
          'note',
          'other'
        ]
      )
    ),
  interaction_at timestamptz not null default now(),
  notes text,
  outcome text,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists company_crm_status_idx on radar.company_crm (status);
create index if not exists company_crm_priority_idx on radar.company_crm (priority);
create index if not exists company_crm_assigned_user_id_idx on radar.company_crm (assigned_user_id);
create index if not exists company_crm_next_action_at_idx on radar.company_crm (next_action_at);
create index if not exists company_crm_last_contact_at_idx on radar.company_crm (last_contact_at);
create index if not exists company_crm_do_not_contact_idx on radar.company_crm (do_not_contact);

create index if not exists company_crm_interactions_company_id_idx
  on radar.company_crm_interactions (company_id, interaction_at desc);
create index if not exists company_crm_interactions_created_by_idx
  on radar.company_crm_interactions (created_by);

create index if not exists market_companies_city_idx on radar.market_companies (city);
create index if not exists market_companies_state_idx on radar.market_companies (state);
create index if not exists market_companies_category_idx on radar.market_companies (category);
create index if not exists market_companies_cnpj_validation_status_idx
  on radar.market_companies (cnpj_validation_status);
create index if not exists market_companies_name_trgm_ready_idx
  on radar.market_companies (lower(name));

create index if not exists company_partners_company_decision_idx
  on radar.company_partners (company_id, decision_priority nulls last, is_administrator desc, partner_name);

create index if not exists company_contacts_company_whatsapp_idx
  on radar.company_contacts (company_id)
  where is_whatsapp = true or likely_whatsapp = true;

drop trigger if exists set_company_crm_updated_at on radar.company_crm;
create trigger set_company_crm_updated_at
before update on radar.company_crm
for each row
execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- 2) Grants + RLS (somente platform admin no client authenticated)
-- ---------------------------------------------------------------------------

grant usage on schema radar to authenticated;

grant select on radar.market_companies to authenticated;
grant select on radar.company_cnpj_candidates to authenticated;
grant select on radar.company_partners to authenticated;
grant select on radar.company_contacts to authenticated;
grant select on radar.company_people to authenticated;

grant select, insert, update on radar.company_crm to authenticated;
grant select, insert on radar.company_crm_interactions to authenticated;
grant usage, select on all sequences in schema radar to authenticated;

alter table radar.market_companies enable row level security;
alter table radar.company_cnpj_candidates enable row level security;
alter table radar.company_partners enable row level security;
alter table radar.company_contacts enable row level security;
alter table radar.company_people enable row level security;
alter table radar.company_crm enable row level security;
alter table radar.company_crm_interactions enable row level security;

drop policy if exists radar_market_companies_select_platform_admin on radar.market_companies;
create policy radar_market_companies_select_platform_admin
on radar.market_companies
for select
to authenticated
using (public.is_platform_admin());

drop policy if exists radar_company_cnpj_candidates_select_platform_admin on radar.company_cnpj_candidates;
create policy radar_company_cnpj_candidates_select_platform_admin
on radar.company_cnpj_candidates
for select
to authenticated
using (public.is_platform_admin());

drop policy if exists radar_company_partners_select_platform_admin on radar.company_partners;
create policy radar_company_partners_select_platform_admin
on radar.company_partners
for select
to authenticated
using (public.is_platform_admin());

drop policy if exists radar_company_contacts_select_platform_admin on radar.company_contacts;
create policy radar_company_contacts_select_platform_admin
on radar.company_contacts
for select
to authenticated
using (public.is_platform_admin());

drop policy if exists radar_company_people_select_platform_admin on radar.company_people;
create policy radar_company_people_select_platform_admin
on radar.company_people
for select
to authenticated
using (public.is_platform_admin());

drop policy if exists radar_company_crm_select_platform_admin on radar.company_crm;
create policy radar_company_crm_select_platform_admin
on radar.company_crm
for select
to authenticated
using (public.is_platform_admin());

drop policy if exists radar_company_crm_insert_platform_admin on radar.company_crm;
create policy radar_company_crm_insert_platform_admin
on radar.company_crm
for insert
to authenticated
with check (public.is_platform_admin());

drop policy if exists radar_company_crm_update_platform_admin on radar.company_crm;
create policy radar_company_crm_update_platform_admin
on radar.company_crm
for update
to authenticated
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists radar_company_crm_interactions_select_platform_admin on radar.company_crm_interactions;
create policy radar_company_crm_interactions_select_platform_admin
on radar.company_crm_interactions
for select
to authenticated
using (public.is_platform_admin());

drop policy if exists radar_company_crm_interactions_insert_platform_admin on radar.company_crm_interactions;
create policy radar_company_crm_interactions_insert_platform_admin
on radar.company_crm_interactions
for insert
to authenticated
with check (public.is_platform_admin());

-- ---------------------------------------------------------------------------
-- 3) Helpers internos
-- ---------------------------------------------------------------------------

create or replace function radar.crm_effective_status(p_status text, p_do_not_contact boolean)
returns text
language sql
immutable
as $$
  select case
    when coalesce(p_do_not_contact, false) then 'do_not_contact'
    when p_status is null or btrim(p_status) = '' then 'new'
    else p_status
  end;
$$;

create or replace function radar.crm_company_matches_search(p_company_id bigint, p_search text)
returns boolean
language sql
stable
as $$
  with term as (
    select nullif(lower(btrim(p_search)), '') as q
  )
  select
    case
      when (select q from term) is null then true
      else exists (
        select 1
        from radar.market_companies mc
        left join radar.company_cnpj_candidates cand
          on cand.company_id = mc.id
         and cand.is_selected = true
        where mc.id = p_company_id
          and (
            lower(coalesce(mc.name, '')) like '%' || (select q from term) || '%'
            or lower(coalesce(mc.legal_name, '')) like '%' || (select q from term) || '%'
            or lower(coalesce(mc.trade_name, '')) like '%' || (select q from term) || '%'
            or lower(coalesce(cand.legal_name, '')) like '%' || (select q from term) || '%'
            or lower(coalesce(cand.trade_name, '')) like '%' || (select q from term) || '%'
            or lower(coalesce(cand.cnpj_data ->> 'legal_name', '')) like '%' || (select q from term) || '%'
            or lower(coalesce(cand.cnpj_data ->> 'trade_name', '')) like '%' || (select q from term) || '%'
            or (
              regexp_replace((select q from term), '[^0-9]', '', 'g') <> ''
              and regexp_replace(coalesce(mc.cnpj, ''), '[^0-9]', '', 'g')
                like '%' || regexp_replace((select q from term), '[^0-9]', '', 'g') || '%'
            )
            or (
              regexp_replace((select q from term), '[^0-9]', '', 'g') <> ''
              and regexp_replace(coalesce(mc.cnpj_formatted, ''), '[^0-9]', '', 'g')
                like '%' || regexp_replace((select q from term), '[^0-9]', '', 'g') || '%'
            )
            or lower(coalesce(mc.phone, '')) like '%' || (select q from term) || '%'
            or lower(coalesce(mc.phone_unformatted, '')) like '%' || (select q from term) || '%'
            or lower(coalesce(mc.city, '')) like '%' || (select q from term) || '%'
            or exists (
              select 1
              from radar.company_partners cp
              where cp.company_id = mc.id
                and lower(coalesce(cp.partner_name, '')) like '%' || (select q from term) || '%'
            )
            or exists (
              select 1
              from radar.company_contacts cc
              where cc.company_id = mc.id
                and (
                  lower(coalesce(cc.display_value, '')) like '%' || (select q from term) || '%'
                  or lower(coalesce(cc.normalized_value, '')) like '%' || (select q from term) || '%'
                )
            )
          )
      )
    end;
$$;

-- ---------------------------------------------------------------------------
-- 4) RPC: listagem paginada
-- ---------------------------------------------------------------------------

create or replace function public.radar_crm_list_companies(
  p_search text default null,
  p_statuses text[] default null,
  p_priorities text[] default null,
  p_city text default null,
  p_state text default null,
  p_category text default null,
  p_has_instagram boolean default null,
  p_has_phone boolean default null,
  p_has_whatsapp boolean default null,
  p_has_website boolean default null,
  p_cnpj_validated boolean default null,
  p_registration_active boolean default null,
  p_has_administrator boolean default null,
  p_assigned_user_id uuid default null,
  p_next_action_from timestamptz default null,
  p_next_action_to timestamptz default null,
  p_without_contact boolean default null,
  p_overdue_next_action boolean default null,
  p_page integer default 1,
  p_page_size integer default 25
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, radar
as $$
declare
  v_page integer := greatest(coalesce(p_page, 1), 1);
  v_page_size integer := least(greatest(coalesce(p_page_size, 25), 1), 100);
  v_offset integer;
  v_total bigint;
  v_filtered bigint;
  v_items jsonb;
begin
  if not public.is_platform_admin() then
    raise exception 'Acesso negado: apenas administradores da plataforma.';
  end if;

  v_offset := (v_page - 1) * v_page_size;

  select count(*) into v_total from radar.market_companies;

  with base as (
    select
      mc.id,
      mc.name,
      mc.category,
      mc.city,
      mc.state,
      mc.address,
      mc.phone,
      mc.phone_unformatted,
      mc.whatsapp,
      mc.website,
      mc.instagram_url,
      mc.facebook_url,
      mc.tiktok_url,
      mc.linkedin_url,
      mc.email,
      mc.rating,
      mc.reviews_count,
      mc.google_maps_url,
      mc.cnpj,
      mc.cnpj_formatted,
      mc.cnpj_validation_status,
      mc.legal_name as company_legal_name,
      mc.trade_name as company_trade_name,
      cand.legal_name as candidate_legal_name,
      cand.trade_name as candidate_trade_name,
      cand.cnpj_data ->> 'legal_name' as cnpj_legal_name,
      cand.cnpj_data ->> 'trade_name' as cnpj_trade_name,
      cand.cnpj_data ->> 'registration_status' as cnpj_registration_status,
      cand.cnpj_data ->> 'registration_status_normalized' as cnpj_registration_status_normalized,
      (cand.cnpj_data ->> 'is_active')::boolean as cnpj_is_active,
      coalesce(crm.status, 'new') as crm_status,
      coalesce(crm.priority, 'medium') as crm_priority,
      crm.assigned_user_id,
      crm.last_contact_at,
      crm.next_action_at,
      crm.next_action_description,
      coalesce(crm.do_not_contact, false) as do_not_contact,
      crm.lost_reason,
      assignee.full_name as assigned_user_name,
      assignee.email as assigned_user_email,
      (
        select count(*)::int
        from radar.company_partners cp
        where cp.company_id = mc.id
      ) as partners_count,
      (
        select count(*)::int
        from radar.company_partners cp
        where cp.company_id = mc.id
          and cp.is_administrator = true
      ) as administrators_count,
      (
        select jsonb_build_object(
          'id', cp.id,
          'name', cp.partner_name,
          'qualification', cp.qualification,
          'is_administrator', cp.is_administrator,
          'is_probable_decision_maker', cp.is_probable_decision_maker,
          'decision_priority', cp.decision_priority
        )
        from radar.company_partners cp
        where cp.company_id = mc.id
        order by
          cp.decision_priority asc nulls last,
          cp.is_administrator desc,
          cp.is_probable_decision_maker desc,
          cp.partner_name asc
        limit 1
      ) as primary_decision_maker,
      (
        select cc.display_value
        from radar.company_contacts cc
        where cc.company_id = mc.id
          and (cc.is_whatsapp = true or cc.likely_whatsapp = true)
        order by cc.is_whatsapp desc, cc.is_primary desc, cc.contact_order nulls last, cc.id
        limit 1
      ) as whatsapp_display,
      exists (
        select 1
        from radar.company_contacts cc
        where cc.company_id = mc.id
          and (cc.is_whatsapp = true or cc.likely_whatsapp = true)
      ) or nullif(btrim(coalesce(mc.whatsapp, '')), '') is not null as has_whatsapp,
      nullif(btrim(coalesce(mc.instagram_url, '')), '') is not null as has_instagram,
      nullif(btrim(coalesce(mc.phone, '')), '') is not null
        or nullif(btrim(coalesce(mc.phone_unformatted, '')), '') is not null
        or exists (
          select 1 from radar.company_contacts cc where cc.company_id = mc.id
        ) as has_phone,
      nullif(btrim(coalesce(mc.website, '')), '') is not null as has_website,
      (mc.cnpj_validation_status = 'validated' and mc.cnpj is not null) as cnpj_validated,
      exists (
        select 1
        from radar.company_partners cp
        where cp.company_id = mc.id
          and cp.is_administrator = true
      ) as has_administrator
    from radar.market_companies mc
    left join radar.company_crm crm on crm.company_id = mc.id
    left join public.profiles assignee on assignee.id = crm.assigned_user_id
    left join lateral (
      select c.*
      from radar.company_cnpj_candidates c
      where c.company_id = mc.id
        and c.is_selected = true
      order by c.validated_at desc nulls last, c.id desc
      limit 1
    ) cand on true
  ),
  filtered as (
    select *
    from base b
    where radar.crm_company_matches_search(b.id, p_search)
      and (
        p_statuses is null
        or cardinality(p_statuses) = 0
        or radar.crm_effective_status(b.crm_status, b.do_not_contact) = any (p_statuses)
      )
      and (
        p_priorities is null
        or cardinality(p_priorities) = 0
        or b.crm_priority = any (p_priorities)
      )
      and (p_city is null or btrim(p_city) = '' or lower(coalesce(b.city, '')) = lower(btrim(p_city)))
      and (p_state is null or btrim(p_state) = '' or lower(coalesce(b.state, '')) = lower(btrim(p_state)))
      and (p_category is null or btrim(p_category) = '' or lower(coalesce(b.category, '')) = lower(btrim(p_category)))
      and (p_has_instagram is null or b.has_instagram = p_has_instagram)
      and (p_has_phone is null or b.has_phone = p_has_phone)
      and (p_has_whatsapp is null or b.has_whatsapp = p_has_whatsapp)
      and (p_has_website is null or b.has_website = p_has_website)
      and (p_cnpj_validated is null or b.cnpj_validated = p_cnpj_validated)
      and (
        p_registration_active is null
        or (
          p_registration_active = true
          and (
            coalesce(b.cnpj_is_active, false) = true
            or lower(coalesce(b.cnpj_registration_status_normalized, '')) = 'ativa'
            or lower(coalesce(b.cnpj_registration_status, '')) = 'ativa'
          )
        )
        or (
          p_registration_active = false
          and not (
            coalesce(b.cnpj_is_active, false) = true
            or lower(coalesce(b.cnpj_registration_status_normalized, '')) = 'ativa'
            or lower(coalesce(b.cnpj_registration_status, '')) = 'ativa'
          )
        )
      )
      and (p_has_administrator is null or b.has_administrator = p_has_administrator)
      and (p_assigned_user_id is null or b.assigned_user_id = p_assigned_user_id)
      and (p_next_action_from is null or b.next_action_at >= p_next_action_from)
      and (p_next_action_to is null or b.next_action_at <= p_next_action_to)
      and (
        p_without_contact is null
        or p_without_contact = false
        or b.last_contact_at is null
      )
      and (
        p_overdue_next_action is null
        or p_overdue_next_action = false
        or (b.next_action_at is not null and b.next_action_at < now())
      )
  )
  select count(*) into v_filtered from filtered;

  select coalesce(
    jsonb_agg(row_to_json(page_rows)::jsonb order by page_rows.name asc, page_rows.id asc),
    '[]'::jsonb
  )
  into v_items
  from (
    select
      f.id,
      f.name,
      coalesce(
        nullif(f.cnpj_legal_name, ''),
        nullif(f.candidate_legal_name, ''),
        nullif(f.company_legal_name, '')
      ) as legal_name,
      coalesce(
        nullif(f.cnpj_trade_name, ''),
        nullif(f.candidate_trade_name, ''),
        nullif(f.company_trade_name, '')
      ) as trade_name,
      f.category,
      f.city,
      f.state,
      f.address,
      f.phone,
      f.phone_unformatted,
      coalesce(f.whatsapp_display, f.whatsapp) as whatsapp,
      f.has_whatsapp,
      f.website,
      f.instagram_url,
      f.facebook_url,
      f.tiktok_url,
      f.linkedin_url,
      f.email,
      f.rating,
      f.reviews_count,
      f.google_maps_url,
      f.cnpj,
      f.cnpj_formatted,
      f.cnpj_validated,
      f.cnpj_validation_status,
      f.cnpj_registration_status,
      f.has_instagram,
      f.has_phone,
      f.has_website,
      f.has_administrator,
      f.partners_count,
      f.administrators_count,
      f.primary_decision_maker,
      radar.crm_effective_status(f.crm_status, f.do_not_contact) as status,
      f.crm_priority as priority,
      f.assigned_user_id,
      f.assigned_user_name,
      f.assigned_user_email,
      f.last_contact_at,
      f.next_action_at,
      f.next_action_description,
      f.do_not_contact,
      f.lost_reason,
      (f.next_action_at is not null and f.next_action_at < now()) as next_action_overdue
    from filtered f
    order by f.name asc, f.id asc
    offset v_offset
    limit v_page_size
  ) page_rows;

  return jsonb_build_object(
    'total', v_total,
    'filtered', v_filtered,
    'page', v_page,
    'page_size', v_page_size,
    'items', v_items
  );
end;
$$;

revoke all on function public.radar_crm_list_companies(
  text, text[], text[], text, text, text, boolean, boolean, boolean, boolean,
  boolean, boolean, boolean, uuid, timestamptz, timestamptz, boolean, boolean, integer, integer
) from public, anon;
grant execute on function public.radar_crm_list_companies(
  text, text[], text[], text, text, text, boolean, boolean, boolean, boolean,
  boolean, boolean, boolean, uuid, timestamptz, timestamptz, boolean, boolean, integer, integer
) to authenticated;

-- ---------------------------------------------------------------------------
-- 5) RPC: detalhe da empresa
-- ---------------------------------------------------------------------------

create or replace function public.radar_crm_get_company(p_company_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, radar
as $$
declare
  v_result jsonb;
begin
  if not public.is_platform_admin() then
    raise exception 'Acesso negado: apenas administradores da plataforma.';
  end if;

  select jsonb_build_object(
    'company', to_jsonb(mc) - 'cnpj_raw_data' - 'cnpj_candidate_data' - 'cnpj_validation_data' - 'cnpj_validation_reasons' - 'instagram_profiles',
    'crm', to_jsonb(crm),
    'assigned_user', case
      when assignee.id is null then null
      else jsonb_build_object(
        'id', assignee.id,
        'full_name', assignee.full_name,
        'email', assignee.email
      )
    end,
    'validated_cnpj', case
      when cand.id is null then null
      else jsonb_build_object(
        'id', cand.id,
        'cnpj', cand.cnpj,
        'cnpj_formatted', cand.cnpj_formatted,
        'legal_name', coalesce(cand.cnpj_data ->> 'legal_name', cand.legal_name),
        'trade_name', coalesce(cand.cnpj_data ->> 'trade_name', cand.trade_name),
        'registration_status', cand.cnpj_data ->> 'registration_status',
        'registration_status_normalized', cand.cnpj_data ->> 'registration_status_normalized',
        'is_active', (cand.cnpj_data ->> 'is_active')::boolean,
        'opening_date', cand.cnpj_data ->> 'opening_date',
        'legal_nature', cand.cnpj_data ->> 'legal_nature',
        'company_size', cand.cnpj_data ->> 'company_size',
        'mei_option', cand.cnpj_data ->> 'mei_option',
        'main_cnae_code', cand.cnpj_data ->> 'main_cnae_code',
        'main_cnae_description', cand.cnpj_data ->> 'main_cnae_description',
        'secondary_cnaes', coalesce(cand.cnpj_data -> 'secondary_cnaes', '[]'::jsonb),
        'city', cand.cnpj_data ->> 'city',
        'state', cand.cnpj_data ->> 'state',
        'full_address', cand.cnpj_data ->> 'full_address',
        'is_selected', cand.is_selected,
        'is_validated', cand.is_validated,
        'validation_status', cand.validation_status
      )
    end,
    'partners', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', cp.id,
          'partner_name', cp.partner_name,
          'qualification', cp.qualification,
          'is_administrator', cp.is_administrator,
          'is_probable_decision_maker', cp.is_probable_decision_maker,
          'decision_priority', cp.decision_priority,
          'age_range', cp.age_range,
          'joined_at', cp.joined_at,
          'partner_document_masked', cp.partner_document_masked,
          'source', cp.source
        )
        order by
          cp.decision_priority asc nulls last,
          cp.is_administrator desc,
          cp.is_probable_decision_maker desc,
          cp.partner_name asc
      )
      from radar.company_partners cp
      where cp.company_id = mc.id
    ), '[]'::jsonb),
    'contacts', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', cc.id,
          'contact_type', cc.contact_type,
          'display_value', cc.display_value,
          'normalized_value', cc.normalized_value,
          'is_whatsapp', cc.is_whatsapp,
          'likely_whatsapp', cc.likely_whatsapp,
          'is_primary', cc.is_primary
        )
        order by cc.is_primary desc, cc.is_whatsapp desc, cc.contact_order nulls last, cc.id
      )
      from radar.company_contacts cc
      where cc.company_id = mc.id
    ), '[]'::jsonb),
    'interactions', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', i.id,
          'interaction_type', i.interaction_type,
          'interaction_at', i.interaction_at,
          'notes', i.notes,
          'outcome', i.outcome,
          'created_by', i.created_by,
          'created_by_name', p.full_name,
          'created_by_email', p.email,
          'created_at', i.created_at
        )
        order by i.interaction_at desc, i.id desc
      )
      from radar.company_crm_interactions i
      left join public.profiles p on p.id = i.created_by
      where i.company_id = mc.id
    ), '[]'::jsonb)
  )
  into v_result
  from radar.market_companies mc
  left join radar.company_crm crm on crm.company_id = mc.id
  left join public.profiles assignee on assignee.id = crm.assigned_user_id
  left join lateral (
    select c.*
    from radar.company_cnpj_candidates c
    where c.company_id = mc.id
      and c.is_selected = true
    order by c.validated_at desc nulls last, c.id desc
    limit 1
  ) cand on true
  where mc.id = p_company_id;

  if v_result is null then
    raise exception 'Empresa não encontrada.';
  end if;

  return v_result;
end;
$$;

revoke all on function public.radar_crm_get_company(bigint) from public, anon;
grant execute on function public.radar_crm_get_company(bigint) to authenticated;

-- ---------------------------------------------------------------------------
-- 6) RPC: upsert CRM
-- ---------------------------------------------------------------------------

create or replace function public.radar_crm_upsert_company(
  p_company_id bigint,
  p_status text default null,
  p_priority text default null,
  p_assigned_user_id uuid default null,
  p_clear_assigned_user boolean default false,
  p_next_action_at timestamptz default null,
  p_clear_next_action boolean default false,
  p_next_action_description text default null,
  p_lost_reason text default null,
  p_do_not_contact boolean default null,
  p_last_contact_at timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, radar
as $$
declare
  v_row radar.company_crm%rowtype;
  v_status text;
begin
  if not public.is_platform_admin() then
    raise exception 'Acesso negado: apenas administradores da plataforma.';
  end if;

  if not exists (select 1 from radar.market_companies where id = p_company_id) then
    raise exception 'Empresa não encontrada.';
  end if;

  insert into radar.company_crm (company_id)
  values (p_company_id)
  on conflict (company_id) do nothing;

  select * into v_row from radar.company_crm where company_id = p_company_id for update;

  v_status := coalesce(p_status, v_row.status);

  if p_do_not_contact = true then
    v_status := 'do_not_contact';
  end if;

  if v_status = 'lost' and nullif(btrim(coalesce(p_lost_reason, v_row.lost_reason, '')), '') is null then
    raise exception 'Informe o motivo da perda ao marcar como Perdido.';
  end if;

  update radar.company_crm
  set
    status = v_status,
    priority = coalesce(p_priority, priority),
    assigned_user_id = case
      when p_clear_assigned_user then null
      when p_assigned_user_id is not null then p_assigned_user_id
      else assigned_user_id
    end,
    next_action_at = case
      when p_clear_next_action then null
      when p_next_action_at is not null then p_next_action_at
      else next_action_at
    end,
    next_action_description = case
      when p_clear_next_action then null
      when p_next_action_description is not null then p_next_action_description
      else next_action_description
    end,
    lost_reason = case
      when v_status = 'lost' then coalesce(nullif(btrim(p_lost_reason), ''), lost_reason)
      when p_status is not null and p_status <> 'lost' then null
      else lost_reason
    end,
    do_not_contact = case
      when p_do_not_contact is not null then p_do_not_contact
      when v_status = 'do_not_contact' then true
      when p_status is not null and p_status <> 'do_not_contact' then false
      else do_not_contact
    end,
    last_contact_at = coalesce(p_last_contact_at, last_contact_at),
    updated_at = now()
  where company_id = p_company_id
  returning * into v_row;

  return to_jsonb(v_row);
end;
$$;

revoke all on function public.radar_crm_upsert_company(
  bigint, text, text, uuid, boolean, timestamptz, boolean, text, text, boolean, timestamptz
) from public, anon;
grant execute on function public.radar_crm_upsert_company(
  bigint, text, text, uuid, boolean, timestamptz, boolean, text, text, boolean, timestamptz
) to authenticated;

-- ---------------------------------------------------------------------------
-- 7) RPC: registrar interação
-- ---------------------------------------------------------------------------

create or replace function public.radar_crm_add_interaction(
  p_company_id bigint,
  p_interaction_type text,
  p_notes text default null,
  p_outcome text default null,
  p_interaction_at timestamptz default null,
  p_status text default null,
  p_next_action_at timestamptz default null,
  p_next_action_description text default null,
  p_clear_next_action boolean default false,
  p_priority text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, radar
as $$
declare
  v_interaction radar.company_crm_interactions%rowtype;
  v_crm jsonb;
  v_at timestamptz := coalesce(p_interaction_at, now());
begin
  if not public.is_platform_admin() then
    raise exception 'Acesso negado: apenas administradores da plataforma.';
  end if;

  if not exists (select 1 from radar.market_companies where id = p_company_id) then
    raise exception 'Empresa não encontrada.';
  end if;

  insert into radar.company_crm_interactions (
    company_id,
    interaction_type,
    interaction_at,
    notes,
    outcome,
    created_by
  )
  values (
    p_company_id,
    p_interaction_type,
    v_at,
    p_notes,
    p_outcome,
    auth.uid()
  )
  returning * into v_interaction;

  v_crm := public.radar_crm_upsert_company(
    p_company_id := p_company_id,
    p_status := p_status,
    p_priority := p_priority,
    p_next_action_at := p_next_action_at,
    p_clear_next_action := p_clear_next_action,
    p_next_action_description := p_next_action_description,
    p_last_contact_at := v_at
  );

  return jsonb_build_object(
    'interaction', to_jsonb(v_interaction),
    'crm', v_crm
  );
end;
$$;

revoke all on function public.radar_crm_add_interaction(
  bigint, text, text, text, timestamptz, text, timestamptz, text, boolean, text
) from public, anon;
grant execute on function public.radar_crm_add_interaction(
  bigint, text, text, text, timestamptz, text, timestamptz, text, boolean, text
) to authenticated;

-- ---------------------------------------------------------------------------
-- 8) RPC: opções de filtro + admins da plataforma
-- ---------------------------------------------------------------------------

create or replace function public.radar_crm_filter_options()
returns jsonb
language plpgsql
stable
security definer
set search_path = public, radar
as $$
begin
  if not public.is_platform_admin() then
    raise exception 'Acesso negado: apenas administradores da plataforma.';
  end if;

  return jsonb_build_object(
    'cities', coalesce((
      select jsonb_agg(distinct city order by city)
      from radar.market_companies
      where city is not null and btrim(city) <> ''
    ), '[]'::jsonb),
    'states', coalesce((
      select jsonb_agg(distinct state order by state)
      from radar.market_companies
      where state is not null and btrim(state) <> ''
    ), '[]'::jsonb),
    'categories', coalesce((
      select jsonb_agg(distinct category order by category)
      from radar.market_companies
      where category is not null and btrim(category) <> ''
    ), '[]'::jsonb),
    'assignees', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', p.id,
          'full_name', p.full_name,
          'email', p.email
        )
        order by coalesce(p.full_name, p.email)
      )
      from public.profiles p
      where p.is_platform_admin = true
    ), '[]'::jsonb)
  );
end;
$$;

revoke all on function public.radar_crm_filter_options() from public, anon;
grant execute on function public.radar_crm_filter_options() to authenticated;
