create table public.financeiro_lancamentos (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  evento_id bigint,
  tipo text not null,
  categoria text not null,
  origem text not null,
  valor numeric(12, 2) not null,
  data_lancamento date not null,
  descricao text,
  observacao text,
  referencia_tipo text,
  referencia_id bigint,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint financeiro_lancamentos_tipo_check check (tipo in ('entrada', 'saida')),
  constraint financeiro_lancamentos_origem_check check (origem in ('pagamento', 'upsell', 'manual')),
  constraint financeiro_lancamentos_valor_check check (valor > 0),
  constraint financeiro_lancamentos_evento_tenant_fkey
    foreign key (evento_id, tenant_id)
    references public.eventos(id, tenant_id)
    on delete cascade
);

create index financeiro_lancamentos_tenant_data_idx
  on public.financeiro_lancamentos (tenant_id, data_lancamento desc);

create index financeiro_lancamentos_tenant_evento_idx
  on public.financeiro_lancamentos (tenant_id, evento_id, data_lancamento desc)
  where evento_id is not null;

create unique index financeiro_lancamentos_pagamento_referencia_uidx
  on public.financeiro_lancamentos (tenant_id, referencia_tipo, referencia_id)
  where referencia_tipo = 'evento_pagamento';

create trigger set_financeiro_lancamentos_updated_at
before update on public.financeiro_lancamentos
for each row
execute function public.set_updated_at();

alter table public.financeiro_lancamentos enable row level security;

create policy "financeiro_lancamentos_select_members"
on public.financeiro_lancamentos
for select
to authenticated
using (public.is_tenant_member(tenant_id));

create policy "financeiro_lancamentos_insert_admins"
on public.financeiro_lancamentos
for insert
to authenticated
with check (public.has_tenant_role(tenant_id, array['owner', 'admin']));

create policy "financeiro_lancamentos_update_admins"
on public.financeiro_lancamentos
for update
to authenticated
using (public.has_tenant_role(tenant_id, array['owner', 'admin']))
with check (public.has_tenant_role(tenant_id, array['owner', 'admin']));

create policy "financeiro_lancamentos_delete_admins"
on public.financeiro_lancamentos
for delete
to authenticated
using (public.has_tenant_role(tenant_id, array['owner', 'admin']));

create policy "financeiro_lancamentos_select_platform_admin"
on public.financeiro_lancamentos
for select
to authenticated
using (public.is_platform_admin());

create or replace function public.sync_financeiro_lancamento_from_pagamento()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.financeiro_lancamentos (
      tenant_id,
      evento_id,
      tipo,
      categoria,
      origem,
      valor,
      data_lancamento,
      descricao,
      observacao,
      referencia_tipo,
      referencia_id,
      created_by,
      updated_by
    ) values (
      new.tenant_id,
      new.evento_id,
      'entrada',
      'pagamento',
      'pagamento',
      new.valor,
      new.data_pagamento,
      coalesce(nullif(trim(new.observacao), ''), 'Pagamento recebido'),
      new.observacao,
      'evento_pagamento',
      new.id,
      new.created_by,
      new.updated_by
    );
    return new;
  elsif tg_op = 'UPDATE' then
    update public.financeiro_lancamentos
    set
      evento_id = new.evento_id,
      valor = new.valor,
      data_lancamento = new.data_pagamento,
      descricao = coalesce(nullif(trim(new.observacao), ''), 'Pagamento recebido'),
      observacao = new.observacao,
      updated_by = new.updated_by,
      updated_at = now()
    where referencia_tipo = 'evento_pagamento'
      and referencia_id = new.id
      and tenant_id = new.tenant_id;
    return new;
  elsif tg_op = 'DELETE' then
    delete from public.financeiro_lancamentos
    where referencia_tipo = 'evento_pagamento'
      and referencia_id = old.id
      and tenant_id = old.tenant_id;
    return old;
  end if;

  return null;
end;
$$;

create trigger sync_financeiro_lancamento_from_pagamento_trigger
after insert or update or delete on public.evento_pagamentos
for each row
execute function public.sync_financeiro_lancamento_from_pagamento();

insert into public.financeiro_lancamentos (
  tenant_id,
  evento_id,
  tipo,
  categoria,
  origem,
  valor,
  data_lancamento,
  descricao,
  observacao,
  referencia_tipo,
  referencia_id,
  created_by,
  updated_by,
  created_at,
  updated_at
)
select
  ep.tenant_id,
  ep.evento_id,
  'entrada',
  'pagamento',
  'pagamento',
  ep.valor,
  ep.data_pagamento,
  coalesce(nullif(trim(ep.observacao), ''), 'Pagamento recebido'),
  ep.observacao,
  'evento_pagamento',
  ep.id,
  ep.created_by,
  ep.updated_by,
  ep.created_at,
  ep.updated_at
from public.evento_pagamentos ep
on conflict do nothing;
