do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'eventos_id_tenant_id_key'
      and conrelid = 'public.eventos'::regclass
  ) then
    alter table public.eventos
      add constraint eventos_id_tenant_id_key unique (id, tenant_id);
  end if;
end $$;

create table public.evento_pagamentos (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  evento_id bigint not null,
  data_pagamento date not null,
  valor numeric(12, 2) not null,
  metodo text,
  observacao text,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint evento_pagamentos_evento_tenant_fkey
    foreign key (evento_id, tenant_id)
    references public.eventos(id, tenant_id)
    on delete cascade,
  constraint evento_pagamentos_valor_check check (valor > 0)
);

create table public.evento_tarefas (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  evento_id bigint not null,
  titulo text not null,
  concluida boolean not null default false,
  ordem integer not null default 0,
  data_limite date,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint evento_tarefas_evento_tenant_fkey
    foreign key (evento_id, tenant_id)
    references public.eventos(id, tenant_id)
    on delete cascade,
  constraint evento_tarefas_titulo_check check (char_length(trim(titulo)) > 0)
);

create table public.evento_notas (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  evento_id bigint not null,
  texto text not null,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint evento_notas_evento_tenant_fkey
    foreign key (evento_id, tenant_id)
    references public.eventos(id, tenant_id)
    on delete cascade,
  constraint evento_notas_texto_check check (char_length(trim(texto)) > 0)
);

create index evento_pagamentos_tenant_evento_idx
  on public.evento_pagamentos (tenant_id, evento_id, data_pagamento desc);
create index evento_tarefas_tenant_evento_idx
  on public.evento_tarefas (tenant_id, evento_id, concluida, ordem);
create index evento_notas_tenant_evento_idx
  on public.evento_notas (tenant_id, evento_id, created_at desc);

create trigger set_evento_pagamentos_updated_at
before update on public.evento_pagamentos
for each row
execute function public.set_updated_at();

create trigger set_evento_tarefas_updated_at
before update on public.evento_tarefas
for each row
execute function public.set_updated_at();

create trigger set_evento_notas_updated_at
before update on public.evento_notas
for each row
execute function public.set_updated_at();

alter table public.evento_pagamentos enable row level security;
alter table public.evento_tarefas enable row level security;
alter table public.evento_notas enable row level security;

create policy "evento_pagamentos_select_members"
on public.evento_pagamentos
for select
to authenticated
using (public.is_tenant_member(tenant_id));

create policy "evento_pagamentos_insert_members"
on public.evento_pagamentos
for insert
to authenticated
with check (public.is_tenant_member(tenant_id));

create policy "evento_pagamentos_update_members"
on public.evento_pagamentos
for update
to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

create policy "evento_pagamentos_delete_admins"
on public.evento_pagamentos
for delete
to authenticated
using (public.has_tenant_role(tenant_id, array['owner', 'admin']));

create policy "evento_tarefas_select_members"
on public.evento_tarefas
for select
to authenticated
using (public.is_tenant_member(tenant_id));

create policy "evento_tarefas_insert_members"
on public.evento_tarefas
for insert
to authenticated
with check (public.is_tenant_member(tenant_id));

create policy "evento_tarefas_update_members"
on public.evento_tarefas
for update
to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

create policy "evento_tarefas_delete_members"
on public.evento_tarefas
for delete
to authenticated
using (public.is_tenant_member(tenant_id));

create policy "evento_notas_select_members"
on public.evento_notas
for select
to authenticated
using (public.is_tenant_member(tenant_id));

create policy "evento_notas_insert_members"
on public.evento_notas
for insert
to authenticated
with check (public.is_tenant_member(tenant_id));

create policy "evento_notas_update_members"
on public.evento_notas
for update
to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

create policy "evento_notas_delete_members"
on public.evento_notas
for delete
to authenticated
using (public.is_tenant_member(tenant_id));
