create table public.tenant_packages (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  name text not null,
  description text not null default '',
  buffet jsonb not null default '{"salgados":[],"doces":[],"bebidas":[]}'::jsonb,
  estrutura jsonb not null default '{"brinquedos":[],"espaco":[],"decoracao":[]}'::jsonb,
  equipe jsonb not null default '{"garcom":0,"monitora":0,"limpeza":0}'::jsonb,
  pricing_tiers jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_packages_name_check check (char_length(trim(name)) > 0)
);

create table public.tenant_additionals (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  name text not null,
  price numeric(12, 2) not null default 0,
  category text not null default 'outros',
  type text not null default 'fixo',
  active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_additionals_name_check check (char_length(trim(name)) > 0),
  constraint tenant_additionals_price_check check (price >= 0),
  constraint tenant_additionals_category_check check (category in ('buffet', 'estrutura', 'equipe', 'entretenimento', 'outros')),
  constraint tenant_additionals_type_check check (type in ('fixo', 'por_unidade'))
);

create table public.tenant_commercial_plans (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  nome text not null,
  setup_tipo text not null default 'avista',
  setup_valor numeric(12, 2) not null default 0,
  setup_parcelas integer,
  mensalidade_valor numeric(12, 2) not null default 0,
  fidelidade_meses integer,
  ativo boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_commercial_plans_nome_check check (char_length(trim(nome)) > 0),
  constraint tenant_commercial_plans_setup_tipo_check check (setup_tipo in ('avista', 'parcelado')),
  constraint tenant_commercial_plans_values_check check (
    setup_valor >= 0
    and mensalidade_valor >= 0
    and (setup_parcelas is null or setup_parcelas > 0)
    and (fidelidade_meses is null or fidelidade_meses >= 0)
  )
);

create table public.tenant_checklist_categories (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  name text not null,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_checklist_categories_id_tenant_id_key unique (id, tenant_id),
  constraint tenant_checklist_categories_name_check check (char_length(trim(name)) > 0)
);

create table public.tenant_checklist_items (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  category_id bigint not null,
  label text not null,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_checklist_items_category_tenant_fkey
    foreign key (category_id, tenant_id)
    references public.tenant_checklist_categories(id, tenant_id)
    on delete cascade,
  constraint tenant_checklist_items_label_check check (char_length(trim(label)) > 0)
);

create table public.tenant_message_templates (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  key text not null,
  title text not null,
  body text not null default '',
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_message_templates_key_unique unique (tenant_id, key),
  constraint tenant_message_templates_title_check check (char_length(trim(title)) > 0)
);

create table public.tenant_financial_settings (
  tenant_id bigint primary key references public.tenants(id) on delete cascade,
  default_down_payment_percentage numeric(5, 2) not null default 30,
  max_installments integer not null default 3,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_financial_settings_values_check check (
    default_down_payment_percentage >= 0
    and default_down_payment_percentage <= 100
    and max_installments >= 1
  )
);

create index tenant_packages_tenant_idx on public.tenant_packages (tenant_id, active);
create index tenant_additionals_tenant_idx on public.tenant_additionals (tenant_id, active);
create index tenant_commercial_plans_tenant_idx on public.tenant_commercial_plans (tenant_id, ativo);
create index tenant_checklist_categories_tenant_idx on public.tenant_checklist_categories (tenant_id, sort_order);
create index tenant_checklist_items_category_idx on public.tenant_checklist_items (tenant_id, category_id, sort_order);
create index tenant_message_templates_tenant_idx on public.tenant_message_templates (tenant_id);

create trigger set_tenant_packages_updated_at before update on public.tenant_packages
for each row execute function public.set_updated_at();
create trigger set_tenant_additionals_updated_at before update on public.tenant_additionals
for each row execute function public.set_updated_at();
create trigger set_tenant_commercial_plans_updated_at before update on public.tenant_commercial_plans
for each row execute function public.set_updated_at();
create trigger set_tenant_checklist_categories_updated_at before update on public.tenant_checklist_categories
for each row execute function public.set_updated_at();
create trigger set_tenant_checklist_items_updated_at before update on public.tenant_checklist_items
for each row execute function public.set_updated_at();
create trigger set_tenant_message_templates_updated_at before update on public.tenant_message_templates
for each row execute function public.set_updated_at();
create trigger set_tenant_financial_settings_updated_at before update on public.tenant_financial_settings
for each row execute function public.set_updated_at();

alter table public.tenant_packages enable row level security;
alter table public.tenant_additionals enable row level security;
alter table public.tenant_commercial_plans enable row level security;
alter table public.tenant_checklist_categories enable row level security;
alter table public.tenant_checklist_items enable row level security;
alter table public.tenant_message_templates enable row level security;
alter table public.tenant_financial_settings enable row level security;

create policy "tenant_packages_members_all" on public.tenant_packages
for all to authenticated using (public.is_tenant_member(tenant_id)) with check (public.is_tenant_member(tenant_id));
create policy "tenant_additionals_members_all" on public.tenant_additionals
for all to authenticated using (public.is_tenant_member(tenant_id)) with check (public.is_tenant_member(tenant_id));
create policy "tenant_commercial_plans_members_all" on public.tenant_commercial_plans
for all to authenticated using (public.is_tenant_member(tenant_id)) with check (public.is_tenant_member(tenant_id));
create policy "tenant_checklist_categories_members_all" on public.tenant_checklist_categories
for all to authenticated using (public.is_tenant_member(tenant_id)) with check (public.is_tenant_member(tenant_id));
create policy "tenant_checklist_items_members_all" on public.tenant_checklist_items
for all to authenticated using (public.is_tenant_member(tenant_id)) with check (public.is_tenant_member(tenant_id));
create policy "tenant_message_templates_members_all" on public.tenant_message_templates
for all to authenticated using (public.is_tenant_member(tenant_id)) with check (public.is_tenant_member(tenant_id));
create policy "tenant_financial_settings_members_all" on public.tenant_financial_settings
for all to authenticated using (public.is_tenant_member(tenant_id)) with check (public.is_tenant_member(tenant_id));
