create table public.agent_change_requests (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants (id) on delete cascade,
  created_by uuid references public.profiles (id) on delete set null,
  title text not null,
  request_type text not null,
  impact_area text,
  description text not null,
  desired_example text,
  urgency text not null default 'normal',
  status text not null default 'pending',
  billing_status text not null default 'not_defined',
  estimated_price numeric(12, 2),
  reviewed_at timestamptz,
  approved_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agent_change_requests_request_type_check check (
    request_type in (
      'text_adjustment',
      'info_update',
      'new_faq',
      'flow_change',
      'commercial_rule',
      'automation_integration',
      'other'
    )
  ),
  constraint agent_change_requests_impact_area_check check (
    impact_area is null
    or impact_area in (
      'initial_support',
      'quote',
      'packages',
      'schedule',
      'after_sales',
      'faq',
      'other'
    )
  ),
  constraint agent_change_requests_urgency_check check (urgency in ('low', 'normal', 'high')),
  constraint agent_change_requests_status_check check (
    status in (
      'pending',
      'in_review',
      'waiting_client',
      'quoted',
      'approved',
      'in_progress',
      'completed',
      'rejected'
  )
  ),
  constraint agent_change_requests_billing_status_check check (
    billing_status in ('not_defined', 'included', 'billable', 'billed', 'waived')
  )
);

comment on table public.agent_change_requests is 'Solicitações de ajuste no agente FestaAI por tenant; notas internas em agent_change_request_internal.';

create index agent_change_requests_tenant_id_created_at_idx on public.agent_change_requests (tenant_id, created_at desc);

create index agent_change_requests_status_idx on public.agent_change_requests (status);

create index agent_change_requests_urgency_idx on public.agent_change_requests (urgency);

create table public.agent_change_request_internal (
  request_id bigint primary key references public.agent_change_requests (id) on delete cascade,
  admin_notes text,
  updated_at timestamptz not null default now()
);

comment on table public.agent_change_request_internal is 'Campos exclusivos da equipe FestaAI (notas internas) por solicitação.';

create trigger set_agent_change_requests_updated_at
before update on public.agent_change_requests
for each row
execute function public.set_updated_at ();

create trigger set_agent_change_request_internal_updated_at
before update on public.agent_change_request_internal
for each row
execute function public.set_updated_at ();

alter table public.agent_change_requests enable row level security;

alter table public.agent_change_request_internal enable row level security;

-- Tenant admins: list/read own tenant
create policy "agent_change_requests_select_tenant_admins"
on public.agent_change_requests
for select
to authenticated
using (public.has_tenant_role (tenant_id, array['owner', 'admin']));

-- Tenant admins: create (only initial workflow values)
create policy "agent_change_requests_insert_tenant_admins"
on public.agent_change_requests
for insert
to authenticated
with check (
  public.has_tenant_role (tenant_id, array['owner', 'admin'])
  and created_by = auth.uid()
  and status = 'pending'
  and billing_status = 'not_defined'
  and estimated_price is null
  and reviewed_at is null
  and approved_at is null
  and completed_at is null
);

-- Tenant admins: delete only before implementation by platform team
create policy "agent_change_requests_delete_tenant_admins"
on public.agent_change_requests
for delete
to authenticated
using (
  public.has_tenant_role (tenant_id, array['owner', 'admin'])
  and status not in ('in_progress', 'completed')
);

-- Platform admin: full read
create policy "agent_change_requests_select_platform_admin"
on public.agent_change_requests
for select
to authenticated
using (public.is_platform_admin ());

-- Platform admin: operational update (status, billing, timestamps, etc.)
create policy "agent_change_requests_update_platform_admin"
on public.agent_change_requests
for update
to authenticated
using (public.is_platform_admin ())
with check (public.is_platform_admin ());

-- Internal notes: platform admin only
create policy "agent_change_request_internal_select_platform_admin"
on public.agent_change_request_internal
for select
to authenticated
using (public.is_platform_admin ());

create policy "agent_change_request_internal_insert_platform_admin"
on public.agent_change_request_internal
for insert
to authenticated
with check (public.is_platform_admin ());

create policy "agent_change_request_internal_update_platform_admin"
on public.agent_change_request_internal
for update
to authenticated
using (public.is_platform_admin ())
with check (public.is_platform_admin ());
