-- Fase 2.1: configuração de automação inbound por tenant e logs de dispatch para N8N.

create table public.tenant_automation_settings (
  tenant_id bigint primary key references public.tenants (id) on delete cascade,
  inbound_automation_enabled boolean not null default false,
  n8n_routing_key text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_tenant_automation_settings_updated_at
before update on public.tenant_automation_settings
for each row execute function public.set_updated_at();

alter table public.tenant_automation_settings enable row level security;

create policy "tenant_automation_settings_select_tenant_member"
on public.tenant_automation_settings
for select to authenticated
using (public.is_tenant_member (tenant_id));

create policy "tenant_automation_settings_insert_tenant_admin"
on public.tenant_automation_settings
for insert to authenticated
with check (public.has_tenant_role (tenant_id, array['owner', 'admin']));

create policy "tenant_automation_settings_update_tenant_admin"
on public.tenant_automation_settings
for update to authenticated
using (public.has_tenant_role (tenant_id, array['owner', 'admin']))
with check (public.has_tenant_role (tenant_id, array['owner', 'admin']));

create table public.automation_dispatch_logs (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants (id) on delete set null,
  connection_id bigint references public.whatsapp_connections (id) on delete set null,
  direction text not null,
  event text not null,
  message_id text,
  customer_phone text,
  instance_name text,
  n8n_status text not null default 'pending',
  n8n_response_status integer,
  payload jsonb,
  error_message text,
  created_at timestamptz not null default now(),
  constraint automation_dispatch_logs_direction_check check (
    direction in ('inbound_to_n8n', 'outbound_from_n8n')
  ),
  constraint automation_dispatch_logs_n8n_status_check check (
    n8n_status in ('pending', 'sent', 'failed', 'skipped')
  )
);

create index automation_dispatch_logs_tenant_created_idx
  on public.automation_dispatch_logs (tenant_id, created_at desc);

create index automation_dispatch_logs_connection_id_idx
  on public.automation_dispatch_logs (connection_id);

create index automation_dispatch_logs_n8n_status_idx
  on public.automation_dispatch_logs (n8n_status)
  where n8n_status in ('pending', 'failed');

create unique index automation_dispatch_logs_inbound_dedupe_idx
  on public.automation_dispatch_logs (connection_id, message_id, event, direction)
  where direction = 'inbound_to_n8n' and message_id is not null;

alter table public.automation_dispatch_logs enable row level security;

create policy "automation_dispatch_logs_no_client_access"
on public.automation_dispatch_logs
for all to anon, authenticated
using (false)
with check (false);

revoke all on table public.automation_dispatch_logs from anon, authenticated;
grant all on table public.automation_dispatch_logs to service_role;
