create table public.calendar_blocks (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  data date not null,
  motivo text,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint calendar_blocks_tenant_data_key unique (tenant_id, data)
);

create index calendar_blocks_tenant_data_idx
  on public.calendar_blocks (tenant_id, data);

create trigger set_calendar_blocks_updated_at
before update on public.calendar_blocks
for each row
execute function public.set_updated_at();

alter table public.calendar_blocks enable row level security;

create policy "calendar_blocks_select_members"
on public.calendar_blocks
for select
to authenticated
using (public.is_tenant_member(tenant_id));

create policy "calendar_blocks_insert_members"
on public.calendar_blocks
for insert
to authenticated
with check (public.is_tenant_member(tenant_id));

create policy "calendar_blocks_update_members"
on public.calendar_blocks
for update
to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

create policy "calendar_blocks_delete_members"
on public.calendar_blocks
for delete
to authenticated
using (public.is_tenant_member(tenant_id));
