-- Feriados adicionais por tenant (estadual / municipal / empresa).
-- Datas automáticas (nacionais oficiais e facultativos comerciais) não são duplicadas aqui.

create or replace function public.date_month(d date)
returns integer
language sql
immutable
parallel safe
as $$ select extract(month from d)::integer $$;

create or replace function public.date_day(d date)
returns integer
language sql
immutable
parallel safe
as $$ select extract(day from d)::integer $$;

create table public.tenant_holidays (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants (id) on delete cascade,
  holiday_date date not null,
  name text not null,
  scope text not null,
  kind text not null,
  recurs_annually boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_holidays_scope_check
    check (scope in ('state', 'municipal', 'tenant')),
  constraint tenant_holidays_kind_check
    check (kind in ('official', 'optional', 'custom')),
  constraint tenant_holidays_name_check
    check (char_length(btrim(name)) between 1 and 120)
);

comment on table public.tenant_holidays is
  'Feriados adicionais do tenant. Datas automáticas da precificação não são armazenadas aqui.';

comment on column public.tenant_holidays.holiday_date is
  'Data de referência. Se recurs_annually=true, o match usa só dia/mês; senão, a data completa.';

comment on column public.tenant_holidays.scope is
  'Abrangência: state | municipal | tenant.';

comment on column public.tenant_holidays.kind is
  'Tipo comercial: official | optional | custom.';

create trigger set_tenant_holidays_updated_at
before update on public.tenant_holidays
for each row
execute function public.set_updated_at();

-- Unicidade: mesmo tenant + data (ou dia/mês) + scope + kind + nome normalizado.
-- Inclui inativos para impedir duplicata histórica; a UI deve oferecer reativação.
create unique index tenant_holidays_unique_one_shot
  on public.tenant_holidays (
    tenant_id,
    holiday_date,
    scope,
    kind,
    lower(btrim(name))
  )
  where not recurs_annually;

create unique index tenant_holidays_unique_recurring_md
  on public.tenant_holidays (
    tenant_id,
    public.date_month(holiday_date),
    public.date_day(holiday_date),
    scope,
    kind,
    lower(btrim(name))
  )
  where recurs_annually;

create index tenant_holidays_tenant_active_idx
  on public.tenant_holidays (tenant_id)
  where active;

create index tenant_holidays_tenant_date_idx
  on public.tenant_holidays (tenant_id, holiday_date);

alter table public.tenant_holidays enable row level security;

create policy "tenant_holidays_select_tenant_member"
on public.tenant_holidays
for select
to authenticated
using (
  public.is_tenant_member(tenant_id)
  or public.is_platform_admin()
);

create policy "tenant_holidays_insert_tenant_admin"
on public.tenant_holidays
for insert
to authenticated
with check (
  public.has_tenant_role(tenant_id, array['owner', 'admin'])
  or public.is_platform_admin()
);

create policy "tenant_holidays_update_tenant_admin"
on public.tenant_holidays
for update
to authenticated
using (
  public.has_tenant_role(tenant_id, array['owner', 'admin'])
  or public.is_platform_admin()
)
with check (
  public.has_tenant_role(tenant_id, array['owner', 'admin'])
  or public.is_platform_admin()
);

create policy "tenant_holidays_delete_tenant_admin"
on public.tenant_holidays
for delete
to authenticated
using (
  public.has_tenant_role(tenant_id, array['owner', 'admin'])
  or public.is_platform_admin()
);
